"""Admin panel HTML patch for products, branding, policies, and currencies."""
from __future__ import annotations

def patch_admin_html(document: str) -> str:
    if "data-page=\"management\"" in document:
        return document
    document = document.replace('src="/app-icon.svg"', 'src="/v1/storefront/branding/icon"')
    nav_marker = '<button class="nav-btn" data-view="categories">▦ الأقسام</button>'
    nav_extra = nav_marker + '<button class="nav-btn" data-view="products">▤ المنتجات</button><button class="nav-btn" data-view="management">⚙ الشعار والسياسات</button>'
    document = document.replace(nav_marker, nav_extra, 1)
    sections = r'''
        <section class="view" data-page="products"><div class="section"><div class="section-head"><div><h2>إدارة ظهور المنتجات</h2><p>التعديلات محفوظة محليًا ولا تلغيها مزامنة JS4Card</p></div><button class="ghost" id="reloadManagedProducts">تحديث</button></div><div class="filter"><input class="input" id="managedProductSearch" placeholder="ابحث باسم المنتج..."><select class="select" id="managedProductVisibility" style="max-width:180px"><option value="all">الكل</option><option value="visible">الظاهرة</option><option value="hidden">المخفية</option></select></div><div id="managedProductList"><div class="loading">جاري تحميل المنتجات...</div></div></div></section>
        <section class="view" data-page="management"><div class="section"><div class="section-head"><div><h2>شعار المتجر وأيقونة التطبيق</h2><p>ارفع الصور من الهاتف، ويمكنك إعادتها للوضع الافتراضي</p></div></div><div class="grid2"><div class="brand-editor"><img id="managedLogoPreview" src="/v1/storefront/branding/logo" alt=""><div class="field"><label>شعار المتجر</label><input class="input" id="managedLogoFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></div><div class="actions"><button class="primary" data-save-brand="logo">حفظ الشعار</button><button class="danger" data-reset-brand="logo">إعادة الافتراضي</button></div></div><div class="brand-editor"><img class="brand-icon" id="managedIconPreview" src="/v1/storefront/branding/icon" alt=""><div class="field"><label>أيقونة التطبيق</label><input class="input" id="managedIconFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></div><div class="actions"><button class="primary" data-save-brand="icon">حفظ الأيقونة</button><button class="danger" data-reset-brand="icon">إعادة الافتراضي</button></div></div></div></div><div class="section"><div class="section-head"><div><h2>العملات والسياسات</h2><p>تظهر السياسات أسفل المتجر، وأسعار التحويل تستخدم لعرض العملات</p></div><button class="primary" id="saveManagementSettings">حفظ</button></div><div id="managementSettings" class="loading">جاري تحميل الإعدادات...</div></div></section>
'''
    document = document.replace("      </div>\n    </main>", sections + "      </div>\n    </main>", 1)
    css = r'''
    .managed-product-row{display:grid;grid-template-columns:minmax(220px,1.5fr) minmax(120px,.7fr) 105px 105px auto;gap:10px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:16px;background:var(--panel2);margin-bottom:10px}.managed-product-row b{font-size:11px}.managed-product-row small{display:block;margin-top:5px;color:var(--muted);font-size:8px}.brand-editor{padding:14px;border:1px solid var(--line);border-radius:17px;background:var(--panel2)}.brand-editor img{width:100%;height:120px;object-fit:contain;border-radius:13px;background:#09090e;margin-bottom:12px}.brand-editor img.brand-icon{width:120px;margin-inline:auto;display:block}.policy-textarea{min-height:150px}
    @media(max-width:820px){.managed-product-row{grid-template-columns:1fr 90px auto}.managed-product-row .managed-provider,.managed-product-row .managed-stock{display:none}}
    @media(max-width:520px){.managed-product-row{grid-template-columns:1fr}.managed-product-row button{width:100%}}
'''
    document = document.replace("  </style>", css + "  </style>", 1)
    document = document.replace(
        "customers:'العملاء والأرصدة'};",
        "customers:'العملاء والأرصدة',products:'المنتجات',management:'الشعار والسياسات'};",
        1,
    )
    document = document.replace(
        "if(name==='customers')loadCustomers()}",
        "if(name==='customers')loadCustomers();if(name==='products')loadManagedProducts();if(name==='management')loadManagement()}",
        1,
    )
    script = r'''
  async function loadManagedProducts(){try{const q=encodeURIComponent($('#managedProductSearch')?.value||''),v=encodeURIComponent($('#managedProductVisibility')?.value||'all');const d=await api(`/v1/storefront/admin/products?q=${q}&visibility=${v}&limit=300`);state.managedProducts=d.items||[];const box=$('#managedProductList');box.innerHTML=state.managedProducts.length?state.managedProducts.map(p=>`<div class="managed-product-row"><div><b>${esc(p.display_name||p.original_name)}</b><small>${esc(p.category_name||'')} • #${p.id}${p.has_override?' • تعديل محلي':''}</small></div><div class="managed-provider"><span class="badge">${esc(p.provider||'يدوي')}</span></div><div class="managed-stock">المخزون: ${p.stock}</div><div>${money(p.price)}</div><button class="${p.is_hidden?'danger':'secondary'} small" data-edit-managed-product="${p.id}">${p.is_hidden?'مخفي • تعديل':'ظاهر • تعديل'}</button></div>`).join(''):'<div class="empty">لا توجد منتجات مطابقة.</div>'}catch(e){toast(e.message,true)}}
  function editManagedProduct(id){const p=(state.managedProducts||[]).find(x=>Number(x.id)===Number(id));if(!p)return;openModal('تعديل ظهور المنتج',`<div class="field"><label>اسم مخصص داخل الموقع (اتركه فارغًا لاستخدام اسم JS4Card)</label><input class="input" id="managedProductName" value="${esc(p.display_name||'')}"></div><div class="field"><label>الترتيب</label><input class="input" id="managedProductSort" type="number" value="${Number(p.sort_order||0)}"></div><label class="check"><input id="managedProductHidden" type="checkbox" ${p.is_hidden?'checked':''}> إخفاء المنتج من الموقع</label><div class="actions" style="margin-top:18px"><button class="primary" data-save-managed-product="${p.id}">حفظ</button><button class="danger" data-reset-managed-product="${p.id}">إلغاء التعديل المحلي</button></div>`)}
  async function saveManagedProduct(id,reset=false){try{const payload=reset?{reset:true}:{display_name:$('#managedProductName').value.trim(),sort_order:Number($('#managedProductSort').value||0),is_hidden:$('#managedProductHidden').checked};await api(`/v1/storefront/admin/products/${id}`,{method:'PUT',body:JSON.stringify(payload)});closeModal();toast(reset?'تمت إعادة المنتج لإعدادات المزود':'تم حفظ إعداد المنتج');loadManagedProducts()}catch(e){toast(e.message,true)}}
  async function loadManagement(){try{const [s,b]=await Promise.all([api('/v1/storefront/admin/settings'),api('/v1/storefront/admin/branding')]);state.settings=s;const pretty=(()=>{try{return JSON.stringify(JSON.parse(s.exchange_rates_json||'{}'),null,2)}catch{return s.exchange_rates_json||'{}'}})();$('#managementSettings').innerHTML=`<div class="grid2"><div class="field"><label>رمز العملة الأساسي</label><input class="input" data-management-setting="currency" value="${esc(s.currency||'USD')}"></div><div class="field"><label>علامة العملة</label><input class="input" data-management-setting="currency_symbol" value="${esc(s.currency_symbol||'$')}"></div></div><div class="field"><label>أسعار العملات بصيغة JSON</label><textarea class="textarea" data-management-setting="exchange_rates_json" dir="ltr">${esc(pretty)}</textarea></div><div class="field"><label>سياسة الخصوصية</label><textarea class="textarea policy-textarea" data-management-setting="privacy_policy">${esc(s.privacy_policy||'')}</textarea></div><div class="field"><label>الشروط والأحكام</label><textarea class="textarea policy-textarea" data-management-setting="terms_policy">${esc(s.terms_policy||'')}</textarea></div><div class="field"><label>سياسة الاسترجاع</label><textarea class="textarea policy-textarea" data-management-setting="refund_policy">${esc(s.refund_policy||'')}</textarea></div>`;$('#managedLogoPreview').src=`${b.logo.url}?v=${Date.now()}`;$('#managedIconPreview').src=`${b.icon.url}?v=${Date.now()}`}catch(e){toast(e.message,true)}}
  async function saveManagementSettings(){const payload={};$$('[data-management-setting]').forEach(i=>payload[i.dataset.managementSetting]=i.value.trim());try{await api('/v1/storefront/admin/settings',{method:'PUT',body:JSON.stringify(payload)});toast('تم حفظ العملات والسياسات')}catch(e){toast(e.message,true)}}
  async function saveBrand(kind,reset=false){try{const file=kind==='logo'?$('#managedLogoFile').files[0]:$('#managedIconFile').files[0];const payload=reset?{delete:true}:{image:await fileData(file)};await api(`/v1/storefront/admin/branding/${kind}`,{method:'PUT',body:JSON.stringify(payload)});toast(reset?'تمت إعادة الصورة الافتراضية':'تم حفظ الصورة');loadManagement()}catch(e){toast(e.message,true)}}
  let managedProductTimer=0;document.addEventListener('input',e=>{if(e.target?.id==='managedProductSearch'){clearTimeout(managedProductTimer);managedProductTimer=setTimeout(loadManagedProducts,280)}});document.addEventListener('change',e=>{if(e.target?.id==='managedProductVisibility')loadManagedProducts()});document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.id==='reloadManagedProducts')loadManagedProducts();if(t.id==='saveManagementSettings')saveManagementSettings();if(t.dataset.editManagedProduct)editManagedProduct(Number(t.dataset.editManagedProduct));if(t.dataset.saveManagedProduct)saveManagedProduct(Number(t.dataset.saveManagedProduct));if(t.dataset.resetManagedProduct)saveManagedProduct(Number(t.dataset.resetManagedProduct),true);if(t.dataset.saveBrand)saveBrand(t.dataset.saveBrand,false);if(t.dataset.resetBrand)saveBrand(t.dataset.resetBrand,true)});
'''
    document = document.replace("  </script>", script + "  </script>", 1)
    return document
