"""Mobile-first Arabic customer app for Uchiha Store."""

STOREFRONT_HTML = r'''<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,maximum-scale=1">
  <meta name="theme-color" content="#08090d">
  <meta name="color-scheme" content="dark">
  <meta name="description" content="Uchiha Store للمنتجات والخدمات الرقمية">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <link rel="manifest" href="/manifest.webmanifest">
  <link rel="icon" href="/app-icon.svg" type="image/svg+xml">
  <title>Uchiha Store</title>
  <style>
    :root{
      --bg:#08090d;--bg-2:#0b0c11;--panel:#121218;--panel-2:#19191f;--panel-3:#222229;
      --text:#f7f4f5;--muted:#9b9295;--line:rgba(228,49,63,.13);
      --primary:#e4313f;--secondary:#9f111b;--accent:#d7d9de;
      --primary-rgb:228,49,63;--secondary-rgb:159,17,27;
      --gold:#d7d9de;--danger:#ff6672;--shadow:0 22px 70px rgba(0,0,0,.5);
      --header:74px;--bottom:84px;--radius:22px;--safe-bottom:env(safe-area-inset-bottom,0px)
    }
    *{box-sizing:border-box}
    html{background:var(--bg);scroll-behavior:smooth}
    body{margin:0;min-height:100vh;background:
      radial-gradient(circle at 90% -10%,rgba(var(--primary-rgb),.14),transparent 29%),
      radial-gradient(circle at -10% 38%,rgba(var(--secondary-rgb),.09),transparent 24%),var(--bg);
      color:var(--text);font-family:Tahoma,"Segoe UI",Arial,sans-serif;-webkit-font-smoothing:antialiased}
    body.locked{overflow:hidden}
    button,input,select,textarea{font:inherit}
    button,a,input,select,textarea{-webkit-tap-highlight-color:transparent}
    button{color:inherit}
    a{color:inherit;text-decoration:none}
    img{display:block;max-width:100%}
    [hidden]{display:none!important}
    :focus-visible{outline:2px solid var(--primary);outline-offset:2px}
    .icon{width:23px;height:23px;display:block;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
    .app{min-height:100vh;padding-bottom:calc(var(--bottom) + var(--safe-bottom) + 16px)}
    .shell{width:min(1120px,calc(100% - 28px));margin-inline:auto}
    .top-accent{height:4px;position:fixed;inset:0 0 auto;z-index:90;background:linear-gradient(90deg,var(--secondary),var(--primary),var(--accent))}
    .header{position:sticky;top:0;z-index:50;height:var(--header);border-bottom:1px solid var(--line);background:rgba(8,9,13,.9);backdrop-filter:blur(18px)}
    .header-inner{height:100%;display:flex;align-items:center;gap:12px}
    .brand{display:flex;align-items:center;gap:10px;margin-inline-end:auto;min-width:0}
    .logo{width:44px;height:44px;border-radius:15px;box-shadow:0 10px 28px rgba(var(--primary-rgb),.17)}
    .brand-copy{min-width:0}.brand-copy b{display:block;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.brand-copy small{color:var(--muted);font-size:9px;letter-spacing:1.1px}
    .head-actions{display:flex;align-items:center;gap:7px}
    .icon-btn{width:42px;height:42px;display:grid;place-items:center;border:1px solid var(--line);border-radius:14px;background:var(--panel);cursor:pointer}
    .icon-btn:active,.nav-btn:active,.category-card:active,.product-card:active{transform:scale(.96)}
    .balance-pill{height:42px;display:flex;align-items:center;gap:7px;padding:0 12px;border:1px solid rgba(var(--primary-rgb),.18);border-radius:14px;background:rgba(var(--primary-rgb),.07);font-size:12px;font-weight:900;white-space:nowrap}
    .balance-pill i{width:7px;height:7px;border-radius:50%;background:var(--primary);box-shadow:0 0 14px var(--primary)}
    .main{padding-top:18px}
    .view{display:none;animation:viewIn .24s ease}.view.active{display:block}@keyframes viewIn{from{opacity:.2;transform:translateY(7px)}to{opacity:1;transform:none}}
    .hero{position:relative;overflow:hidden;border:1px solid rgba(var(--primary-rgb),.25);border-radius:24px;background:var(--panel);box-shadow:var(--shadow),0 0 55px rgba(var(--primary-rgb),.07);aspect-ratio:15/6;min-height:190px}
    .slides{height:100%;display:flex;direction:ltr;transition:transform .7s cubic-bezier(.22,.78,.2,1);will-change:transform}
    .slide{position:relative;flex:0 0 100%;height:100%;overflow:hidden;isolation:isolate;direction:rtl}
    .slide:after{content:"";position:absolute;inset:0;z-index:-1;background:linear-gradient(90deg,rgba(8,9,13,.08),rgba(8,9,13,.64) 58%,rgba(8,9,13,.95))}
    .slide img{position:absolute;inset:0;z-index:-2;width:100%;height:100%;object-fit:cover}
    .slide-copy{height:100%;width:min(54%,600px);display:flex;flex-direction:column;justify-content:center;padding:30px}
    .slide-kicker{display:inline-flex;align-items:center;gap:7px;width:max-content;padding:7px 10px;border:1px solid color-mix(in srgb,var(--slide-accent) 38%,transparent);border-radius:99px;background:color-mix(in srgb,var(--slide-accent) 12%,transparent);color:#f3d6d9;font-size:10px;font-weight:900}
    .slide h2{margin:13px 0 8px;font-size:clamp(23px,4vw,43px);line-height:1.22}.slide p{margin:0;color:#cec6c9;line-height:1.75;font-size:13px;max-width:530px}
    .slide-cta{width:max-content;margin-top:17px;padding:10px 17px;border:0;border-radius:13px;background:var(--slide-accent);color:#fff;font-weight:900;cursor:pointer}
    .slider-dots{position:absolute;right:50%;bottom:13px;z-index:3;display:flex;direction:ltr;gap:6px;transform:translateX(50%)}
    .dot{width:7px;height:7px;padding:0;border:0;border-radius:99px;background:rgba(255,255,255,.38);transition:.3s;cursor:pointer}.dot.active{width:24px;background:var(--primary)}
    .ticker{display:flex;align-items:center;gap:11px;margin:14px 0;padding:12px 15px;border:1px solid var(--line);border-radius:16px;background:rgba(18,18,24,.82);color:#d2cacc;font-size:12px;overflow:hidden}
    .ticker i{width:8px;height:8px;flex:0 0 auto;border-radius:50%;background:var(--primary);box-shadow:0 0 0 5px rgba(var(--primary-rgb),.1)}
    .search-wrap{position:relative;margin:14px 0 18px}.search-wrap .icon{position:absolute;right:16px;top:15px;color:var(--muted)}
    .search{width:100%;height:53px;padding:0 51px 0 16px;border:1px solid var(--line);border-radius:18px;background:var(--panel);color:var(--text);outline:0}.search:focus{border-color:rgba(var(--primary-rgb),.45);box-shadow:0 0 0 4px rgba(var(--primary-rgb),.08)}
    .section-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:18px 0 13px}.section-head h2{margin:0;font-size:20px}.section-head p{margin:5px 0 0;color:var(--muted);font-size:11px}.text-btn{border:0;background:none;color:var(--primary);font-weight:900;cursor:pointer}
    .category-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:13px}
    .category-card{position:relative;overflow:hidden;min-width:0;padding:0;border:1px solid var(--line);border-radius:19px;background:var(--panel);cursor:pointer;transition:.18s;text-align:right}
    .category-card:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--card-accent) 48%,transparent)}
    .category-img{aspect-ratio:1/1;overflow:hidden;background:var(--panel-2)}.category-img img{width:100%;height:100%;object-fit:cover;transition:.35s}.category-card:hover img{transform:scale(1.035)}
    .category-name{padding:11px 10px 12px;font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.category-count{position:absolute;top:8px;left:8px;padding:5px 7px;border:1px solid rgba(255,255,255,.11);border-radius:9px;background:rgba(8,9,13,.76);font-size:9px;color:#e2dcde;backdrop-filter:blur(8px)}
    .product-section{scroll-margin-top:90px;padding-top:11px}.product-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px;padding-bottom:20px}
    .product-card{min-width:0;overflow:hidden;border:1px solid var(--line);border-radius:19px;background:linear-gradient(155deg,var(--panel-2),var(--panel));cursor:pointer;text-align:right;transition:.18s}
    .product-card:hover{transform:translateY(-3px);border-color:rgba(var(--secondary-rgb),.3)}
    .product-img{position:relative;aspect-ratio:1.25/1;overflow:hidden;background:var(--panel-2)}.product-img img{width:100%;height:100%;object-fit:cover}.provider-tag{position:absolute;top:8px;right:8px;padding:5px 7px;border-radius:8px;background:rgba(8,9,13,.78);font-size:8px;color:#ddd7d9}
    .product-body{padding:12px}.product-body h3{min-height:39px;margin:0 0 8px;font-size:12px;line-height:1.62;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.product-meta{display:flex;align-items:center;justify-content:space-between;gap:7px}.price{color:#fff3f4;font-size:14px;font-weight:900}.stock{color:var(--muted);font-size:9px}.buy-mini{width:31px;height:31px;display:grid;place-items:center;border:0;border-radius:10px;background:linear-gradient(135deg,var(--primary),var(--secondary));color:#fff;cursor:pointer}.buy-mini .icon{width:16px;height:16px;stroke-width:2.4}
    .empty,.loading{grid-column:1/-1;padding:38px 18px;border:1px dashed rgba(255,255,255,.12);border-radius:19px;background:rgba(18,18,24,.58);color:var(--muted);text-align:center;line-height:1.8}
    .page-card{border:1px solid var(--line);border-radius:22px;background:var(--panel);padding:20px;margin-bottom:14px}.page-title{display:flex;align-items:center;gap:12px;margin-bottom:18px}.page-title .title-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(135deg,rgba(var(--primary-rgb),.14),rgba(var(--secondary-rgb),.1));color:var(--primary)}.page-title h2{margin:0;font-size:21px}.page-title p{margin:5px 0 0;color:var(--muted);font-size:11px}
    .wallet-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.wallet-card{min-height:118px;padding:17px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,var(--wc1),var(--wc2));position:relative;overflow:hidden}.wallet-card:after{content:"";position:absolute;width:90px;height:90px;left:-25px;bottom:-35px;border:18px solid rgba(255,255,255,.04);border-radius:50%}.wallet-card span{display:block;color:#ddd6d8;font-size:11px}.wallet-card strong{display:block;margin-top:12px;font-size:25px}.wallet-card.primary{--wc1:#641018;--wc2:#181217}.wallet-card.blue{--wc1:#3a151a;--wc2:#17171d}.wallet-card.purple{--wc1:#342a2d;--wc2:#15151a}
    .history{display:grid;gap:9px}.history-row,.order-row,.method-row{display:flex;align-items:center;gap:12px;padding:13px;border:1px solid var(--line);border-radius:16px;background:var(--panel-2)}.history-icon,.method-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:rgba(var(--primary-rgb),.08);color:var(--primary);font-weight:900}.grow{flex:1;min-width:0}.grow b{display:block;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.grow small{display:block;margin-top:5px;color:var(--muted);font-size:9px}.amount{font-size:12px;font-weight:900}.amount.minus{color:#ffb2c0}.amount.plus{color:#f1dadd}
    .status{padding:6px 9px;border-radius:99px;background:rgba(var(--secondary-rgb),.12);color:#f0c8cd;font-size:9px;font-weight:900}.status.completed,.status.approved{background:rgba(215,217,222,.1);color:#eef0f3}.status.pending,.status.processing,.status.waiting_payment{background:rgba(215,217,222,.09);color:#d7d9de}.status.cancelled,.status.rejected{background:rgba(255,104,129,.1);color:#ffafbd}
    .order-row{align-items:flex-start}.order-price{font-size:13px;font-weight:900;text-align:left}.order-price small{display:block;margin-top:7px}
    .link-card{text-align:center;padding:36px 22px}.link-orb{width:100px;height:100px;display:grid;place-items:center;margin:0 auto 20px;border:1px solid rgba(var(--primary-rgb),.3);border-radius:33px;background:radial-gradient(circle,rgba(var(--primary-rgb),.25),rgba(var(--secondary-rgb),.07));box-shadow:0 0 60px rgba(var(--primary-rgb),.11)}.link-orb img{width:66px}.link-card h2{margin:0 0 9px}.link-card p{max-width:610px;margin:0 auto 20px;color:var(--muted);font-size:12px;line-height:1.9}.linked-badge{display:inline-flex;align-items:center;gap:7px;padding:8px 12px;border-radius:99px;background:rgba(var(--primary-rgb),.1);color:#f3d6d9;font-size:11px;font-weight:900}
    .primary-btn,.outline-btn,.danger-btn{min-height:49px;padding:0 20px;border-radius:15px;font-weight:900;cursor:pointer;transition:.18s}.primary-btn{border:0;background:linear-gradient(135deg,var(--primary),var(--secondary));color:#fff;box-shadow:0 14px 35px rgba(var(--primary-rgb),.16)}.outline-btn{border:1px solid var(--line);background:var(--panel-2);color:var(--text)}.danger-btn{border:1px solid rgba(255,104,129,.28);background:rgba(255,104,129,.06);color:#ff9cae}.wide{width:100%}.primary-btn:active,.outline-btn:active,.danger-btn:active{transform:scale(.98)}
    .support-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.support-card{min-height:135px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;border:1px solid var(--line);border-radius:19px;background:var(--panel-2);text-align:center}.support-card .icon{color:var(--primary);width:29px;height:29px}.support-card b{font-size:12px}.support-card small{color:var(--muted);font-size:9px}
    .bottom-nav{position:fixed;z-index:55;right:0;left:0;bottom:0;height:calc(var(--bottom) + var(--safe-bottom));padding-bottom:var(--safe-bottom);border-top:1px solid var(--line);background:rgba(8,9,13,.94);backdrop-filter:blur(20px)}.nav-inner{width:min(680px,100%);height:var(--bottom);display:grid;grid-template-columns:repeat(5,1fr);margin:auto}.nav-btn{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;border:0;background:none;color:#7d7477;font-size:9px;cursor:pointer}.nav-btn .icon{width:22px;height:22px}.nav-btn.active{color:var(--primary)}.nav-btn.home span:first-child{width:54px;height:54px;display:grid;place-items:center;margin-top:-25px;border:1px solid rgba(var(--primary-rgb),.25);border-radius:50%;background:var(--panel);box-shadow:0 0 0 8px rgba(8,9,13,.96),0 8px 30px rgba(0,0,0,.3);color:var(--primary)}.nav-btn.home .icon{width:24px;height:24px}
    .float-tools{position:fixed;z-index:45;left:max(14px,calc((100vw - 1120px)/2 + 10px));bottom:calc(var(--bottom) + var(--safe-bottom) + 18px);display:grid;gap:9px}.float-btn{width:49px;height:49px;display:grid;place-items:center;border:0;border-radius:17px;background:linear-gradient(145deg,var(--primary),var(--secondary));color:#fff;box-shadow:0 12px 30px rgba(var(--primary-rgb),.2);cursor:pointer}.float-btn.muted{background:var(--panel-2);color:var(--text);border:1px solid var(--line)}
    .overlay{position:fixed;inset:0;z-index:80;background:rgba(0,0,0,.72);backdrop-filter:blur(5px);opacity:0;pointer-events:none;transition:.22s}.overlay.show{opacity:1;pointer-events:auto}
    .drawer{position:fixed;z-index:85;inset:0 0 0 auto;width:min(390px,90vw);display:flex;flex-direction:column;border-left:1px solid var(--line);background:#0d0d12;box-shadow:-30px 0 90px rgba(0,0,0,.5);transform:translateX(103%);transition:.3s cubic-bezier(.22,.75,.2,1)}.drawer.show{transform:none}.drawer-head{padding:25px 20px;border-bottom:1px solid var(--line)}.profile-line{display:flex;align-items:center;gap:13px}.avatar{width:53px;height:53px;display:grid;place-items:center;border:1px solid rgba(var(--primary-rgb),.25);border-radius:18px;background:linear-gradient(145deg,rgba(var(--primary-rgb),.16),rgba(var(--secondary-rgb),.12));font-size:19px;font-weight:900}.profile-line h3{margin:0;font-size:15px}.profile-line p{margin:5px 0 0;color:var(--muted);font-size:10px}.drawer-balance{display:flex;align-items:center;justify-content:space-between;margin-top:15px;padding:12px 14px;border:1px solid rgba(var(--primary-rgb),.15);border-radius:15px;background:rgba(var(--primary-rgb),.055);font-size:12px}.drawer-menu{padding:12px;overflow:auto}.menu-btn{width:100%;height:49px;display:flex;align-items:center;gap:13px;padding:0 14px;border:0;border-radius:14px;background:none;color:#d9d3d5;cursor:pointer;text-align:right}.menu-btn:hover,.menu-btn.active{background:var(--panel-2);color:var(--primary)}.menu-btn .icon{width:20px;height:20px}.menu-btn small{margin-inline-start:auto;color:var(--muted)}.drawer-foot{margin-top:auto;padding:16px;border-top:1px solid var(--line)}
    .modal{position:fixed;z-index:100;right:50%;top:50%;width:min(590px,calc(100% - 24px));max-height:min(88vh,800px);overflow:auto;border:1px solid var(--line);border-radius:24px;background:#111116;box-shadow:var(--shadow);transform:translate(50%,-45%) scale(.96);opacity:0;pointer-events:none;transition:.22s}.modal.show{transform:translate(50%,-50%) scale(1);opacity:1;pointer-events:auto}.modal-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;padding:15px 17px;border-bottom:1px solid var(--line);background:rgba(17,17,22,.95);backdrop-filter:blur(14px)}.modal-head b{font-size:14px}.close-btn{width:38px;height:38px;display:grid;place-items:center;border:1px solid var(--line);border-radius:12px;background:var(--panel-2);cursor:pointer}.modal-body{padding:18px}.product-modal-top{display:grid;grid-template-columns:110px 1fr;gap:15px;align-items:center}.product-modal-img{aspect-ratio:1;border-radius:17px;overflow:hidden;background:var(--panel-2)}.product-modal-img img{width:100%;height:100%;object-fit:cover}.product-modal-top h2{margin:0 0 9px;font-size:19px}.modal-price{display:inline-flex;padding:7px 10px;border-radius:10px;background:rgba(var(--secondary-rgb),.13);color:#f0c8cd;font-weight:900}.product-desc{margin:15px 0;color:var(--muted);font-size:11px;line-height:1.8}.field{margin-bottom:12px}.field label{display:block;margin-bottom:7px;color:#ddd6d8;font-size:11px;font-weight:900}.input,.select,.textarea{width:100%;min-height:50px;padding:0 14px;border:1px solid var(--line);border-radius:15px;background:var(--panel-2);color:var(--text);outline:0}.textarea{min-height:90px;padding-top:13px;resize:vertical}.input:focus,.select:focus,.textarea:focus{border-color:rgba(var(--primary-rgb),.42);box-shadow:0 0 0 4px rgba(var(--primary-rgb),.07)}.buy-actions{display:grid;grid-template-columns:1.2fr .8fr;gap:10px;margin-top:17px}.fine-note{margin-top:15px;padding-right:12px;border-right:3px solid var(--primary);color:var(--muted);font-size:10px;line-height:1.75}
    .auth-screen{position:fixed;z-index:200;inset:0;display:grid;place-items:center start;padding:22px max(22px,calc((100vw - 1120px)/2));background:linear-gradient(90deg,rgba(8,9,13,.12),rgba(8,9,13,.68) 48%,rgba(8,9,13,.97)),url("/assets/hero-madara-v2.webp") center/cover no-repeat;overflow:auto}.auth-card{width:min(560px,100%);padding:31px;border:1px solid rgba(var(--primary-rgb),.2);border-radius:26px;background:rgba(16,16,21,.95);box-shadow:0 30px 100px rgba(0,0,0,.6)}.auth-brand{text-align:center;margin-bottom:25px}.auth-brand img{width:72px;margin:0 auto 12px}.auth-brand h1{margin:0;font-size:25px}.auth-brand p{margin:8px 0 0;color:var(--muted);font-size:11px}.auth-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:20px;padding:5px;border:1px solid var(--line);border-radius:16px;background:#0c0c11}.auth-tab{height:43px;border:0;border-radius:12px;background:none;color:var(--muted);font-weight:900;cursor:pointer}.auth-tab.active{background:linear-gradient(135deg,var(--primary),var(--secondary));color:#fff;box-shadow:0 8px 22px rgba(var(--primary-rgb),.16)}.auth-form{display:none}.auth-form.active{display:block}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.full{grid-column:1/-1}.password-wrap{position:relative}.password-wrap button{position:absolute;left:8px;top:7px;width:37px;height:37px;border:0;background:none;color:var(--muted);cursor:pointer}.auth-links{display:flex;align-items:center;justify-content:space-between;margin:12px 2px 17px;font-size:10px}.link-btn{border:0;background:none;color:#ff7781;cursor:pointer}.auth-error{display:none;margin-bottom:13px;padding:11px 12px;border:1px solid rgba(255,104,129,.22);border-radius:13px;background:rgba(255,104,129,.06);color:#ffb0be;font-size:10px;line-height:1.7}.auth-error.show{display:block}.auth-footer{margin-top:17px;color:var(--muted);font-size:9px;line-height:1.7;text-align:center}
    .toast{position:fixed;z-index:300;right:50%;bottom:calc(var(--bottom) + var(--safe-bottom) + 18px);max-width:min(430px,calc(100% - 24px));padding:12px 16px;border:1px solid rgba(var(--primary-rgb),.2);border-radius:14px;background:#1d1719;color:#fff5f6;box-shadow:0 18px 45px rgba(0,0,0,.42);font-size:11px;line-height:1.6;opacity:0;pointer-events:none;transform:translate(50%,15px);transition:.22s}.toast.show{opacity:1;transform:translate(50%,0)}.toast.error{border-color:rgba(255,104,129,.28)}
    .skeleton{position:relative;overflow:hidden;background:var(--panel-2)}.skeleton:after{content:"";position:absolute;inset:0;transform:translateX(100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.055),transparent);animation:shine 1.3s infinite}@keyframes shine{to{transform:translateX(-100%)}}
    @media(max-width:900px){.category-grid{grid-template-columns:repeat(4,1fr)}.product-grid{grid-template-columns:repeat(3,1fr)}.hero{aspect-ratio:12/6}.slide-copy{width:66%}}
    @media(max-width:680px){:root{--header:68px;--bottom:76px}.shell{width:calc(100% - 22px)}.brand-copy{display:none}.header-inner{gap:7px}.balance-pill{padding:0 9px}.hero{min-height:190px;aspect-ratio:16/8.6;border-radius:20px}.slide-copy{width:75%;padding:20px}.slide p{font-size:10px}.slide h2{font-size:23px}.category-grid{grid-template-columns:repeat(3,1fr);gap:10px}.category-name{font-size:10px;padding:9px}.product-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.product-body{padding:9px}.product-body h3{font-size:10px;min-height:34px}.product-img{aspect-ratio:1/1}.price{font-size:11px}.buy-mini{width:28px;height:28px}.wallet-cards{grid-template-columns:1fr}.support-grid{grid-template-columns:1fr 1fr}.float-tools{left:12px}.auth-card{padding:23px 18px}.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.auth-screen{place-items:center;padding:12px;background:linear-gradient(rgba(8,9,13,.76),rgba(8,9,13,.96)),url("/assets/hero-madara-v2.webp") 32% center/cover no-repeat}.modal{bottom:0;top:auto;right:0;width:100%;max-height:91vh;border-radius:24px 24px 0 0;transform:translateY(102%);opacity:1}.modal.show{transform:none}.product-modal-top{grid-template-columns:90px 1fr}.hide-mobile{display:none}}
    @media(max-width:430px){.category-grid{grid-template-columns:repeat(3,1fr)}.product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.hero{aspect-ratio:16/9.5}.slide-copy{width:86%}.slide p{max-width:85%}.head-actions{gap:5px}.icon-btn{width:39px;height:39px}.balance-pill{font-size:10px}.wallet-card strong{font-size:22px}}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}}
  </style>
</head>
<body class="locked">
  <div class="top-accent"></div>
  <div id="app" class="app" hidden>
    <header class="header"><div class="shell header-inner">
      <div class="brand"><img class="logo" src="/app-icon.svg" alt="Uchiha"><div class="brand-copy"><b id="brandName">Uchiha Store</b><small>DIGITAL APP</small></div></div>
      <div class="head-actions">
        <button class="balance-pill" data-view="wallet" aria-label="الرصيد"><i></i><span id="headerBalance">$ 0.00</span></button>
        <button class="icon-btn" aria-label="الإشعارات" data-view="orders"><svg class="icon"><use href="#i-bell"/></svg></button>
        <button class="icon-btn" id="menuButton" aria-label="القائمة"><svg class="icon"><use href="#i-menu"/></svg></button>
      </div>
    </div></header>

    <main class="shell main">
      <section class="view active" data-page="home">
        <div class="hero" id="hero"><div class="slides" id="slides"></div><div class="slider-dots" id="sliderDots"></div></div>
        <div class="ticker"><i></i><span id="announcement">مرحبًا بك في Uchiha Store</span></div>
        <div class="search-wrap"><svg class="icon"><use href="#i-search"/></svg><input class="search" id="searchInput" autocomplete="off" placeholder="ابحث عن لعبة أو بطاقة أو خدمة..."></div>
        <div class="section-head" id="categories"><div><h2>أقسام المتجر</h2><p>اختر القسم المناسب لك</p></div><button class="text-btn" id="allProducts">عرض الكل</button></div>
        <div class="category-grid" id="categoryGrid"><div class="loading">جاري تحميل الأقسام...</div></div>
        <section class="product-section" id="products">
          <div class="section-head"><div><h2 id="productsTitle">أحدث المنتجات</h2><p id="resultCount"></p></div><button class="text-btn" id="loadMore" hidden>المزيد</button></div>
          <div class="product-grid" id="productGrid"><div class="loading">جاري تحميل المنتجات...</div></div>
        </section>
      </section>

      <section class="view" data-page="wallet">
        <div class="page-title"><div class="title-icon"><svg class="icon"><use href="#i-wallet"/></svg></div><div><h2>المحفظة</h2><p>رصيد واحد للموقع وبوت Uchiha</p></div></div>
        <div class="wallet-cards">
          <div class="wallet-card primary"><span>رصيدك الحالي</span><strong id="walletBalance">$ 0.00</strong></div>
          <div class="wallet-card blue"><span>إجمالي مشترياتك</span><strong id="walletPurchases">$ 0.00</strong></div>
          <div class="wallet-card purple"><span>عدد الطلبات</span><strong id="walletOrders">0</strong></div>
        </div>
        <div class="section-head"><div><h2>آخر الحركات</h2><p>الإضافات والمشتريات والاستردادات</p></div><button class="primary-btn" id="depositButton">إضافة رصيد</button></div>
        <div class="history" id="walletHistory"><div class="loading">جاري تحميل المحفظة...</div></div>
      </section>

      <section class="view" data-page="orders">
        <div class="page-title"><div class="title-icon"><svg class="icon"><use href="#i-bag"/></svg></div><div><h2>طلباتي</h2><p>متابعة طلبات JS4Card والتسليم</p></div></div>
        <div class="history" id="ordersList"><div class="loading">جاري تحميل الطلبات...</div></div>
      </section>

      <section class="view" data-page="link">
        <div class="page-card link-card">
          <div class="link-orb"><img src="/app-icon.svg" alt="Uchiha Bot"></div>
          <div id="linkState"><h2>ربط حسابك مع بوت Uchiha</h2><p>اضغط الزر لفتح البوت. رمز الربط سيصل إليه تلقائيًا، وبعدها ستستخدم الرصيد والطلبات نفسها في الموقع والبوت.</p><button class="primary-btn" id="linkBotButton">فتح البوت والربط تلقائيًا</button></div>
        </div>
      </section>

      <section class="view" data-page="support">
        <div class="page-title"><div class="title-icon"><svg class="icon"><use href="#i-headset"/></svg></div><div><h2>الدعم الفني</h2><p id="supportHours">متوفرون لخدمتك</p></div></div>
        <div class="support-grid" id="supportGrid"></div>
      </section>

      <section class="view" data-page="profile">
        <div class="page-card">
          <div class="page-title"><div class="title-icon"><svg class="icon"><use href="#i-user"/></svg></div><div><h2 id="profileName">حسابي</h2><p id="profileEmail"></p></div></div>
          <div class="history" id="profileDetails"></div>
          <div style="display:grid;gap:10px;margin-top:18px"><button class="outline-btn wide" data-view="link">ربط بوت Uchiha</button><button class="danger-btn wide" id="logoutButton">تسجيل الخروج</button></div>
        </div>
      </section>
    </main>

    <div class="float-tools"><button class="float-btn" data-view="support" aria-label="الدعم"><svg class="icon"><use href="#i-headset"/></svg></button><button class="float-btn muted" id="quickMenu" aria-label="المزيد"><svg class="icon"><use href="#i-more"/></svg></button></div>
    <nav class="bottom-nav"><div class="nav-inner">
      <button class="nav-btn" data-view="profile"><span><svg class="icon"><use href="#i-user"/></svg></span><span>حسابي</span></button>
      <button class="nav-btn" data-view="wallet"><span><svg class="icon"><use href="#i-wallet"/></svg></span><span>المحفظة</span></button>
      <button class="nav-btn home active" data-view="home"><span><svg class="icon"><use href="#i-home"/></svg></span><span>الرئيسية</span></button>
      <button class="nav-btn" id="bottomDeposit"><span><svg class="icon"><use href="#i-pluscard"/></svg></span><span>إضافة رصيد</span></button>
      <button class="nav-btn" data-view="orders"><span><svg class="icon"><use href="#i-bag"/></svg></span><span>طلباتي</span></button>
    </div></nav>
  </div>

  <div class="overlay" id="overlay"></div>
  <aside class="drawer" id="drawer" aria-hidden="true">
    <div class="drawer-head"><div class="profile-line"><div class="avatar" id="drawerAvatar">U</div><div><h3 id="drawerName">Uchiha</h3><p id="drawerEmail"></p></div></div><div class="drawer-balance"><span>رصيد المحفظة</span><b id="drawerBalance">$ 0.00</b></div></div>
    <div class="drawer-menu">
      <button class="menu-btn" data-view="home"><svg class="icon"><use href="#i-home"/></svg>الرئيسية</button>
      <button class="menu-btn" id="drawerDeposit"><svg class="icon"><use href="#i-pluscard"/></svg>إضافة رصيد</button>
      <button class="menu-btn" data-view="wallet"><svg class="icon"><use href="#i-wallet"/></svg>محفظتي</button>
      <button class="menu-btn" data-view="orders"><svg class="icon"><use href="#i-bag"/></svg>طلباتي</button>
      <button class="menu-btn" data-view="link"><svg class="icon"><use href="#i-link"/></svg>ربط بوت Uchiha<small id="linkMenuState"></small></button>
      <button class="menu-btn" data-view="support"><svg class="icon"><use href="#i-headset"/></svg>الدعم الفني</button>
      <button class="menu-btn" data-view="profile"><svg class="icon"><use href="#i-user"/></svg>بيانات الحساب</button>
      <button class="menu-btn" id="installApp" hidden><svg class="icon"><use href="#i-download"/></svg>تثبيت التطبيق</button>
    </div>
    <div class="drawer-foot"><button class="danger-btn wide" id="drawerLogout">تسجيل الخروج</button></div>
  </aside>

  <section class="modal" id="productModal" aria-hidden="true"><div class="modal-head"><b>تفاصيل المنتج</b><button class="close-btn" data-close="productModal">✕</button></div><div class="modal-body" id="productModalBody"></div></section>
  <section class="modal" id="depositModal" aria-hidden="true"><div class="modal-head"><b>إضافة رصيد</b><button class="close-btn" data-close="depositModal">✕</button></div><div class="modal-body" id="depositModalBody"></div></section>

  <section class="auth-screen" id="authScreen">
    <div class="auth-card">
      <div class="auth-brand"><img src="/app-icon.svg" alt="Uchiha"><h1>Uchiha Store</h1><p>ادخل إلى عالم Uchiha الرقمي بحساب واحد للموقع والبوت</p></div>
      <div class="auth-tabs"><button class="auth-tab active" data-auth="login">تسجيل الدخول</button><button class="auth-tab" data-auth="signup">إنشاء حساب</button></div>
      <div class="auth-error" id="authError"></div>
      <form class="auth-form active" id="loginForm" data-auth-form="login">
        <div class="field"><label for="loginIdentifier">اسم المستخدم أو البريد الإلكتروني</label><input class="input" id="loginIdentifier" autocomplete="username" required></div>
        <div class="field"><label for="loginPassword">كلمة المرور</label><div class="password-wrap"><input class="input" id="loginPassword" type="password" autocomplete="current-password" required><button type="button" data-toggle-password="loginPassword">◉</button></div></div>
        <div class="auth-links"><button type="button" class="link-btn" id="forgotPassword">نسيت كلمة السر؟</button><span>دخول آمن ومحمي</span></div>
        <button class="primary-btn wide" type="submit">تسجيل الدخول</button>
      </form>
      <form class="auth-form" id="signupForm" data-auth-form="signup">
        <div class="form-grid">
          <div class="field"><label for="firstName">الاسم الأول</label><input class="input" id="firstName" autocomplete="given-name" required></div>
          <div class="field"><label for="lastName">الاسم الأخير</label><input class="input" id="lastName" autocomplete="family-name"></div>
          <div class="field full"><label for="signupUsername">اسم المستخدم</label><input class="input" id="signupUsername" autocomplete="username" required></div>
          <div class="field full"><label for="signupEmail">البريد الإلكتروني</label><input class="input" id="signupEmail" type="email" autocomplete="email" required></div>
          <div class="field"><label for="signupCountry">البلد</label><input class="input" id="signupCountry" autocomplete="country-name" placeholder="مثال: سوريا" required></div>
          <div class="field"><label for="signupPhone">رقم الهاتف</label><input class="input" id="signupPhone" autocomplete="tel" inputmode="tel" placeholder="+963..." required></div>
          <div class="field full"><label for="signupPassword">كلمة المرور (8 أحرف على الأقل)</label><div class="password-wrap"><input class="input" id="signupPassword" type="password" autocomplete="new-password" minlength="8" required><button type="button" data-toggle-password="signupPassword">◉</button></div></div>
        </div>
        <button class="primary-btn wide" type="submit">إنشاء حساب</button>
      </form>
      <div class="auth-footer">هوية Uchiha القرمزية • محفظة وطلبات موحّدة • ربط تيليجرام آمن.</div>
    </div>
  </section>

  <div class="toast" id="toast"></div>

  <svg width="0" height="0" style="position:absolute"><defs>
    <symbol id="i-menu" viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></symbol>
    <symbol id="i-bell" viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></symbol>
    <symbol id="i-home" viewBox="0 0 24 24"><path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/></symbol>
    <symbol id="i-search" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></symbol>
    <symbol id="i-wallet" viewBox="0 0 24 24"><path d="M4 6h15a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h12v3"/><path d="M16 12h5v4h-5a2 2 0 0 1 0-4z"/></symbol>
    <symbol id="i-bag" viewBox="0 0 24 24"><path d="M5 8h14l-1 13H6zM9 8V6a3 3 0 0 1 6 0v2"/></symbol>
    <symbol id="i-user" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></symbol>
    <symbol id="i-pluscard" viewBox="0 0 24 24"><rect x="2" y="5" width="20" height="15" rx="2"/><path d="M2 10h20M17 14v4m-2-2h4"/></symbol>
    <symbol id="i-headset" viewBox="0 0 24 24"><path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14H2v5h4v-5zm16 0h2v5h-4v-5zM18 19c0 2-2 2-4 2"/></symbol>
    <symbol id="i-more" viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></symbol>
    <symbol id="i-link" viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-1 1M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l1-1"/></symbol>
    <symbol id="i-download" viewBox="0 0 24 24"><path d="M12 3v12m-5-5 5 5 5-5M5 21h14"/></symbol>
    <symbol id="i-cart" viewBox="0 0 24 24"><path d="M3 4h2l2 12h11l2-8H7M9 21h.01M18 21h.01"/></symbol>
  </defs></svg>

  <script>
  'use strict';
  const state={account:null,csrf:'',store:{currency:'USD',currency_symbol:'$',exchange_rates:{USD:1},theme:{}},banners:[],categories:[],products:[],page:1,pages:1,total:0,category:'',query:'',slide:0,slideTimer:null,searchTimer:null,currentProduct:null,installPrompt:null,linkPoll:null};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;
  function detailMessage(data,fallback='حدث خطأ غير متوقع.'){const d=data?.detail;return typeof d==='string'?d:(d?.message||data?.message||fallback)}
  async function api(url,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(state.csrf&&options.method&&options.method!=='GET')headers['X-CSRF-Token']=state.csrf;const res=await fetch(url,{credentials:'same-origin',...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok){const e=new Error(detailMessage(data));e.status=res.status;e.data=data;throw e}return data}
  function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.classList.add('show');clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove('show'),3200)}
  function money(value){const n=Number(value||0);try{return new Intl.NumberFormat('ar',{style:'currency',currency:state.store.currency||'USD',maximumFractionDigits:2}).format(n)}catch{return `${n.toFixed(2)} ${state.store.currency||'$'}`}}
  function initials(value){return String(value||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'U'}
  function setLocked(value){document.body.classList.toggle('locked',value)}
  function openOverlay(){setLocked(true);$('#overlay').classList.add('show')}
  function closeLayers(){clearInterval(state.linkPoll);state.linkPoll=null;$('#overlay').classList.remove('show');$('#drawer').classList.remove('show');$$('.modal.show').forEach(x=>x.classList.remove('show'));setLocked(!$('#authScreen').hidden)}
  function openDrawer(){openOverlay();$('#drawer').classList.add('show');$('#drawer').setAttribute('aria-hidden','false')}
  function openModal(id){openOverlay();const el=$('#'+id);el.classList.add('show');el.setAttribute('aria-hidden','false')}
  function applyTheme(){const t=state.store.theme||{};for(const [key,val] of [['--primary',t.primary],['--secondary',t.secondary],['--accent',t.accent]])if(/^#[0-9a-f]{6}$/i.test(val||''))document.documentElement.style.setProperty(key,val);if(t.primary){const m=t.primary.match(/[0-9a-f]{2}/gi);if(m)document.documentElement.style.setProperty('--primary-rgb',m.map(x=>parseInt(x,16)).join(','))}if(t.secondary){const m=t.secondary.match(/[0-9a-f]{2}/gi);if(m)document.documentElement.style.setProperty('--secondary-rgb',m.map(x=>parseInt(x,16)).join(','))}}
  function updateAccountUI(){const a=state.account||{};const name=`${a.first_name||''} ${a.last_name||''}`.trim()||a.username||'Uchiha';$('#brandName').textContent=state.store.name||'Uchiha Store';$('#headerBalance').textContent=money(a.balance);$('#drawerBalance').textContent=money(a.balance);$('#drawerName').textContent=name;$('#drawerEmail').textContent=a.email||'';$('#drawerAvatar').textContent=initials(name);$('#profileName').textContent=name;$('#profileEmail').textContent=a.email||'';$('#linkMenuState').textContent=a.linked?'مرتبط':'غير مرتبط';$('#profileDetails').innerHTML=`<div class="history-row"><div class="history-icon">@</div><div class="grow"><b>اسم المستخدم</b><small>${esc(a.username||'')}</small></div></div><div class="history-row"><div class="history-icon">☎</div><div class="grow"><b>رقم الهاتف</b><small>${esc(a.phone||'')}</small></div></div><div class="history-row"><div class="history-icon">⌖</div><div class="grow"><b>البلد</b><small>${esc(a.country||'')}</small></div></div>`;renderLinkState()}
  function renderLinkState(){if(!state.account)return;const box=$('#linkState');if(state.account.linked){box.innerHTML=`<div class="linked-badge">● الحساب مرتبط</div><h2 style="margin-top:17px">بوت Uchiha متصل بحسابك</h2><p>رصيدك وطلباتك أصبحت مشتركة تلقائيًا بين الموقع والبوت.</p>`}else{box.innerHTML=`<h2>ربط حسابك مع بوت Uchiha</h2><p>اضغط الزر لفتح البوت. رمز الربط سيصل إليه تلقائيًا، وبعدها ستستخدم الرصيد والطلبات نفسها في الموقع والبوت.</p><button class="primary-btn" id="linkBotButton">فتح البوت والربط تلقائيًا</button>`;$('#linkBotButton').onclick=startBotLink}}
  function showView(name){closeLayers();$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.page===name));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='wallet')loadWallet();if(name==='orders')loadOrders();if(name==='link')renderLinkState();if(name==='support')renderSupport()}
  function renderSlides(){const banners=state.banners||[];$('#slides').innerHTML=banners.map((b,i)=>`<article class="slide" style="--slide-accent:${esc(b.accent||'var(--primary)')}"><img src="${esc(b.image_url)}" alt="" ${i?'loading="lazy"':''}><div class="slide-copy"><span class="slide-kicker">✦ إرث UCHIHA</span><h2>${esc(b.title)}</h2><p>${esc(b.subtitle)}</p>${b.cta_label?`<button class="slide-cta" data-target="${esc(b.cta_target)}">${esc(b.cta_label)}</button>`:''}</div></article>`).join('');$('#sliderDots').innerHTML=banners.map((_,i)=>`<button class="dot ${i===0?'active':''}" data-slide="${i}" aria-label="الصورة ${i+1}"></button>`).join('');state.slide=0;$$('.dot').forEach(b=>b.onclick=()=>goSlide(Number(b.dataset.slide),true));$$('.slide-cta').forEach(b=>b.onclick=()=>handleTarget(b.dataset.target));startSlider()}
  function goSlide(index,manual=false){const count=state.banners.length;if(!count)return;state.slide=(index+count)%count;$('#slides').style.transform=`translateX(${-state.slide*100}%)`;$$('.dot').forEach((d,i)=>d.classList.toggle('active',i===state.slide));if(manual)startSlider()}
  function startSlider(){clearInterval(state.slideTimer);if(state.banners.length>1&&!matchMedia('(prefers-reduced-motion: reduce)').matches)state.slideTimer=setInterval(()=>goSlide(state.slide+1),Number(state.store.hero_interval_ms||5200))}
  function handleTarget(target){if(!target)return;if(target==='#categories'||target==='#products'){showView('home');setTimeout(()=>$(target)?.scrollIntoView({behavior:'smooth'}),80)}else if(target==='#bot-link')showView('link');else if(/^https?:\/\//.test(target))window.open(target,'_blank','noopener')}
  function renderCategories(){const roots=state.categories.filter(c=>!c.parent_id&&c.product_count>0);$('#categoryGrid').innerHTML=roots.length?roots.map(c=>`<button class="category-card" style="--card-accent:${esc(c.accent)}" data-category="${c.id}"><div class="category-img"><img src="${esc(c.image_url)}" loading="lazy" alt="${esc(c.name)}"></div><span class="category-count">${c.product_count}</span><div class="category-name">${esc(c.name)}</div></button>`).join(''):'<div class="empty">لا توجد أقسام مفعّلة حاليًا.</div>';$$('[data-category]').forEach(b=>b.onclick=()=>selectCategory(b.dataset.category))}
  function renderProducts(){const grid=$('#productGrid');grid.innerHTML=state.products.length?state.products.map(p=>`<article class="product-card" data-product="${p.id}"><div class="product-img"><img src="${esc(p.image_url)}" loading="lazy" alt=""><span class="provider-tag">${p.provider==='js4card'?'JS4Card':'Uchiha'}</span></div><div class="product-body"><h3>${esc(p.name)}</h3><div class="product-meta"><div><div class="price">${money(p.price)}</div><div class="stock">${esc(p.delivery_time||'متوفر الآن')}</div></div><button class="buy-mini" aria-label="شراء"><svg class="icon"><use href="#i-cart"/></svg></button></div></div></article>`).join(''):'<div class="empty">لم نجد منتجات مطابقة.</div>';$$('[data-product]').forEach(c=>c.onclick=()=>openProduct(Number(c.dataset.product)));$('#resultCount').textContent=`${state.total} منتج`;$('#loadMore').hidden=state.page>=state.pages}
  async function loadCatalog(append=false){if(!append){state.page=1;$('#productGrid').innerHTML='<div class="loading">جاري تحميل المنتجات...</div>'}const params=new URLSearchParams({page:String(state.page),limit:'48'});if(state.category)params.set('category_id',state.category);if(state.query)params.set('q',state.query);try{const data=await api('/v1/storefront/public-catalog?'+params);state.store=data.store||state.store;state.banners=data.banners||[];state.categories=data.categories||[];state.pages=data.products?.pages||0;state.total=data.products?.total||0;const batch=data.products?.items||[];state.products=append?[...state.products,...batch]:batch;document.title=state.store.name||'Uchiha Store';applyTheme();$('#announcement').textContent=state.store.announcement||'';renderSlides();renderCategories();renderProducts();renderSupport();updateAccountUI()}catch(e){$('#productGrid').innerHTML=`<div class="empty">${esc(e.message)}</div>`;toast(e.message,true)}}
  function selectCategory(id){state.category=String(id||'');const cat=state.categories.find(c=>String(c.id)===state.category);$('#productsTitle').textContent=cat?.name||'كل المنتجات';loadCatalog(false).then(()=>$('#products').scrollIntoView({behavior:'smooth'}))}
  async function openProduct(id){try{const p=await api('/v1/storefront/product/'+id);state.currentProduct=p;const variants=p.variants||[];const fields=(p.fields||[]).map(f=>`<div class="field"><label>${esc(f.label)}${f.required?' *':''}</label>${f.options?.length?`<select class="select" data-field="${esc(f.key)}" ${f.required?'required':''}><option value="">اختر...</option>${f.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<input class="input" data-field="${esc(f.key)}" ${f.required?'required':''} placeholder="${esc(f.label)}">`}</div>`).join('');$('#productModalBody').innerHTML=`<div class="product-modal-top"><div class="product-modal-img"><img src="/v1/storefront/media/category/${p.category_id}" alt=""></div><div><h2>${esc(p.name)}</h2><span class="modal-price">${money(p.price)}</span><div style="margin-top:9px;color:var(--muted);font-size:10px">${esc(p.delivery_time||'تنفيذ رقمي')}</div></div></div><div class="product-desc">${esc(p.description||'')}</div>${variants.length?`<div class="field"><label>اختر النوع</label><select class="select" id="variantSelect"><option value="">اختر...</option>${variants.map(v=>`<option value="${v.id}" data-price="${v.price}">${esc(v.name)} — ${money(v.price)}</option>`).join('')}</select></div>`:''}${p.requires_quantity?`<div class="field"><label>العدد (${p.min_qty} - ${p.max_qty})</label><input class="input" id="productQty" type="number" inputmode="numeric" min="${p.min_qty}" max="${p.max_qty}" value="${p.min_qty}"></div>`:''}<div id="dynamicFields">${fields}</div><div class="buy-actions"><button class="primary-btn" id="confirmPurchase">شراء الآن</button><button class="outline-btn" data-close="productModal">إلغاء</button></div><div class="fine-note">سيتم خصم المبلغ من رصيد Uchiha وتنفيذ الطلب مباشرة من JS4Card. لا تضغط زر الشراء مرتين.</div>`;if($('#variantSelect'))$('#variantSelect').onchange=e=>{const opt=e.target.selectedOptions[0];if(opt?.dataset.price)$('.modal-price').textContent=money(opt.dataset.price)};$('#confirmPurchase').onclick=confirmPurchase;$$('[data-close]',$('#productModal')).forEach(b=>b.onclick=closeLayers);openModal('productModal')}catch(e){toast(e.message,true)}}
  async function confirmPurchase(){const p=state.currentProduct;if(!p)return;const button=$('#confirmPurchase');const fields={};let missing='';$$('[data-field]',$('#productModalBody')).forEach(el=>{if(el.required&&!el.value.trim())missing=el.closest('.field').querySelector('label').textContent;fields[el.dataset.field]=el.value.trim()});if(missing){toast(`أكمل الحقل: ${missing}`,true);return}const quantity=Number($('#productQty')?.value||p.min_qty||1),variant_id=Number($('#variantSelect')?.value||0);if(p.variants?.length&&!variant_id){toast('اختر نوع المنتج أولًا',true);return}button.disabled=true;button.textContent='جاري تنفيذ الطلب...';try{const data=await api('/v1/storefront/purchase/'+p.id,{method:'POST',headers:{'Idempotency-Key':uid()},body:JSON.stringify({quantity,variant_id,fields})});closeLayers();toast(data.status==='processing'?`تم تثبيت الطلب #${data.order_id} وجارٍ تنفيذه`:`تم إنشاء الطلب #${data.order_id}`);await refreshAccount();showView('orders')}catch(e){toast(e.message,true);button.disabled=false;button.textContent='شراء الآن'}}
  async function refreshAccount(){try{const data=await api('/v1/storefront/me');state.account=data.account;state.csrf=data.csrf_token;updateAccountUI();return true}catch(e){if(e.status===401)return false;throw e}}
  async function loadWallet(){try{const w=await api('/v1/storefront/wallet');$('#walletBalance').textContent=money(w.balance);$('#walletPurchases').textContent=money(w.purchases);$('#walletOrders').textContent=w.orders;$('#walletHistory').innerHTML=w.items?.length?w.items.map(x=>`<div class="history-row"><div class="history-icon">${x.type==='add'||x.type==='refund'?'＋':'−'}</div><div class="grow"><b>${esc(x.reason||'حركة رصيد')}</b><small>${esc(x.date||'')}</small></div><div class="amount ${x.type==='add'||x.type==='refund'?'plus':'minus'}">${x.type==='add'||x.type==='refund'?'+':'-'} ${money(x.amount)}</div></div>`).join(''):'<div class="empty">لا توجد حركات رصيد بعد.</div>';state.account.balance=w.balance;updateAccountUI()}catch(e){toast(e.message,true)}}
  async function loadOrders(){try{const data=await api('/v1/storefront/orders');$('#ordersList').innerHTML=data.items?.length?data.items.map(o=>`<div class="order-row"><div class="history-icon">#${o.id}</div><div class="grow"><b>${esc(o.product_name)}</b><small>${esc(o.order_date)} • الكمية ${o.quantity}</small>${o.delivery_info?`<small>${esc(o.delivery_info)}</small>`:''}</div><div class="order-price">${money(o.total_price)}<small class="status ${esc(o.status)}">${statusLabel(o.api_status||o.status)}</small></div></div>`).join(''):'<div class="empty">لم تنشئ أي طلب بعد.</div>'}catch(e){toast(e.message,true)}}
  function statusLabel(s){s=String(s||'pending').toLowerCase();if(/complete|done|delivered/.test(s))return'مكتمل';if(/cancel|reject|fail|error/.test(s))return'مرفوض';if(/process|sending|running/.test(s))return'قيد التنفيذ';return'قيد المراجعة'}
  function renderSupport(){const s=state.store.support||{},items=[];if(s.telegram)items.push(['تيليجرام','@'+s.telegram.replace('@',''),'https://t.me/'+s.telegram.replace('@',''),'i-headset']);if(s.whatsapp)items.push(['واتساب',s.whatsapp,'https://wa.me/'+s.whatsapp.replace(/\D/g,''),'i-headset']);if(s.email)items.push(['البريد الإلكتروني',s.email,'mailto:'+s.email,'i-user']);$('#supportHours').textContent=s.hours||'متوفرون لخدمتك';$('#supportGrid').innerHTML=items.length?items.map(x=>`<a class="support-card" href="${esc(x[2])}" target="_blank" rel="noopener"><svg class="icon"><use href="#${x[3]}"/></svg><b>${esc(x[0])}</b><small>${esc(x[1])}</small></a>`).join(''):'<div class="empty" style="grid-column:1/-1">سيضيف صاحب المتجر بيانات الدعم قريبًا.</div>'}
  async function startBotLink(){const button=$('#linkBotButton');if(button){button.disabled=true;button.textContent='جاري إنشاء رابط آمن...'}try{const data=await api('/v1/storefront/bot-link',{method:'POST'});if(data.linked){await refreshAccount();renderLinkState();return}if(!data.bot_url)throw new Error('رابط البوت غير مضبوط بعد');window.open(data.bot_url,'_blank','noopener');toast('افتح البوت واضغط Start؛ سيتم الربط تلقائيًا');clearInterval(state.linkPoll);state.linkPoll=setInterval(async()=>{if(await refreshAccount()&&state.account.linked){clearInterval(state.linkPoll);state.linkPoll=null;renderLinkState();toast('تم ربط البوت بنجاح')}},2200)}catch(e){toast(e.message,true);if(button){button.disabled=false;button.textContent='فتح البوت والربط تلقائيًا'}}}
  async function openDeposit(){closeLayers();openModal('depositModal');$('#depositModalBody').innerHTML='<div class="loading">جاري تحميل طرق الدفع...</div>';try{const data=await api('/v1/storefront/payment-methods');renderDepositMethods(data.items||[])}catch(e){$('#depositModalBody').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
  function renderDepositMethods(methods){$('#depositModalBody').innerHTML=methods.length?`<div class="history">${methods.map(m=>`<button class="method-row" data-method="${m.id}" style="width:100%;color:inherit;text-align:right;cursor:pointer"><div class="method-icon">${esc(m.icon||'◆')}</div><div class="grow"><b>${esc(m.name)}</b><small>${esc(m.details||'')}</small></div><span>‹</span></button>`).join('')}</div>`:'<div class="empty">لا توجد طرق دفع مفعّلة حاليًا.</div>';$$('[data-method]',$('#depositModalBody')).forEach(b=>b.onclick=()=>renderDepositForm(methods.find(m=>m.id===Number(b.dataset.method))))}
  function renderDepositForm(m){$('#depositModalBody').innerHTML=`<div class="page-card" style="margin:0 0 14px"><b>${esc(m.name)}</b><p style="color:var(--muted);font-size:10px;line-height:1.8">${esc(m.details||'')}</p>${m.transfer_value?`<div style="padding:12px;border-radius:13px;background:var(--panel-2);font-size:11px"><small style="color:var(--muted)">${esc(m.transfer_label||'بيانات التحويل')}</small><b style="display:block;margin-top:7px;word-break:break-all">${esc(m.transfer_value)}</b></div>`:''}</div><div class="field"><label>المبلغ ${m.currency?`(${esc(m.currency)})`:''}</label><input class="input" id="depositAmount" type="number" inputmode="decimal" min="${Number(m.min_amount||0)}" max="${Number(m.max_amount||0)||''}" step="0.01" placeholder="${m.min_amount?`الحد الأدنى ${m.min_amount}`:'أدخل المبلغ'}"></div>${m.payment_mode==='auto'?'':`<div class="field"><label>رقم العملية أو ملاحظة التحويل</label><input class="input" id="depositReference" placeholder="رقم العملية"></div><div class="field"><label>صورة إثبات التحويل ${m.proof_required?'*':''}</label><input class="input" id="depositProof" type="file" accept="image/jpeg,image/png,image/webp" style="padding:12px"></div>`}<div class="buy-actions"><button class="primary-btn" id="submitDeposit">${m.payment_mode==='auto'?'إنشاء فاتورة دفع':'إرسال الطلب'}</button><button class="outline-btn" id="backMethods">رجوع</button></div>`;$('#backMethods').onclick=async()=>{const data=await api('/v1/storefront/payment-methods');renderDepositMethods(data.items||[])};$('#submitDeposit').onclick=()=>submitDeposit(m)}
  async function fileData(file){if(!file)return'';if(file.size>3*1024*1024)throw new Error('حجم الصورة يجب ألا يتجاوز 3 ميغابايت');return await new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
  async function submitDeposit(m){const button=$('#submitDeposit'),amount=Number($('#depositAmount').value||0),reference=$('#depositReference')?.value.trim()||'';if(!amount){toast('أدخل المبلغ',true);return}button.disabled=true;button.textContent='جاري الإرسال...';try{const proof=await fileData($('#depositProof')?.files?.[0]);const data=await api('/v1/storefront/deposits',{method:'POST',body:JSON.stringify({method_id:m.id,amount,reference,proof})});if(data.status==='waiting_payment'){const isPay=data.payment_channel==='binance_pay',destination=isPay?`افتح <b>Binance Pay</b> وأرسل <b>${esc(data.expected_amount)} ${esc(data.coin||data.currency)}</b> إلى ${esc(data.destination_label||'Pay ID')}:`:`أرسل <b>${esc(data.expected_amount)} ${esc(data.coin||data.currency)}</b> عبر شبكة <b>${esc(data.network||'TRX')}</b> إلى:`,referenceLabel=esc(data.reference_label||(isPay?'Transaction ID':'TXID / Transaction Hash'));$('#depositModalBody').innerHTML=`<div class="link-card"><div class="linked-badge">فاتورة Binance جاهزة</div><h2>أرسل المبلغ نفسه</h2><p>${destination}</p><div style="padding:14px;border:1px solid var(--line);border-radius:14px;word-break:break-all">${esc(data.address)}</div><p>تنتهي الفاتورة: ${esc(data.expires_at)}</p>${data.reference_required?`<div class="field" style="text-align:right"><label>${referenceLabel} بعد الدفع</label><input class="input" id="autoDepositReference" autocomplete="off" placeholder="الصق ${referenceLabel} الكامل هنا"></div><div id="autoDepositResult" class="fine-note"></div><button class="primary-btn wide" id="verifyAutoDeposit">تحقق وأضف الرصيد</button>`:''}<button class="outline-btn wide" style="margin-top:10px" data-close="depositModal">إغلاق</button></div>`;if($('#verifyAutoDeposit'))$('#verifyAutoDeposit').onclick=()=>verifyAutoDeposit(data.id,isPay);$$('[data-close]',$('#depositModalBody')).forEach(b=>b.onclick=closeLayers)}else{closeLayers();toast(`تم إرسال طلب الشحن #${data.id} للمراجعة`);showView('wallet')}}catch(e){toast(e.message,true);button.disabled=false;button.textContent=m.payment_mode==='auto'?'إنشاء فاتورة دفع':'إرسال الطلب'}}
  async function verifyAutoDeposit(id,isPay=false){const input=$('#autoDepositReference'),button=$('#verifyAutoDeposit'),result=$('#autoDepositResult'),reference=input?.value.trim()||'';if(!reference){toast(`الصق ${isPay?'Transaction ID':'TXID'} بعد تنفيذ الدفع`,true);return}button.disabled=true;button.textContent=isPay?'جارٍ التحقق من Binance Pay...':'جارٍ التحقق من المعاملة...';try{const data=await api(`/v1/storefront/deposits/${id}/verify`,{method:'POST',body:JSON.stringify({reference})});if(data.status==='approved'){result.textContent='تم تأكيد الدفعة وإضافة الرصيد بنجاح.';button.textContent='تمت إضافة الرصيد';input.disabled=true;await refreshAccount();toast('تمت إضافة الرصيد تلقائيًا')}else if(data.status==='pending_review'){result.textContent=data.message||'تم إرسال الدفعة لمراجعة الإدارة.';button.textContent='قيد مراجعة الإدارة';input.disabled=true;toast('تم استلام رقم المعاملة')}else{result.textContent=data.message||'لم تُثبت المعاملة بعد.';button.disabled=false;button.textContent='إعادة التحقق'}}catch(e){result.textContent=e.message;button.disabled=false;button.textContent='إعادة التحقق'}}
  function showAuthTab(name){$$('.auth-tab').forEach(x=>x.classList.toggle('active',x.dataset.auth===name));$$('.auth-form').forEach(x=>x.classList.toggle('active',x.dataset.authForm===name));$('#authError').classList.remove('show')}
  function authError(message){const el=$('#authError');el.textContent=message;el.classList.add('show')}
  async function submitLogin(e){e.preventDefault();const button=e.submitter;button.disabled=true;try{const data=await api('/v1/storefront/auth/login',{method:'POST',body:JSON.stringify({identifier:$('#loginIdentifier').value.trim(),password:$('#loginPassword').value})});state.account=data.account;state.csrf=data.csrf_token;enterApp()}catch(err){authError(err.message)}finally{button.disabled=false}}
  async function submitSignup(e){e.preventDefault();const button=e.submitter;button.disabled=true;try{const data=await api('/v1/storefront/auth/signup',{method:'POST',body:JSON.stringify({first_name:$('#firstName').value.trim(),last_name:$('#lastName').value.trim(),username:$('#signupUsername').value.trim(),email:$('#signupEmail').value.trim(),country:$('#signupCountry').value.trim(),phone:$('#signupPhone').value.trim(),password:$('#signupPassword').value})});state.account=data.account;state.csrf=data.csrf_token;enterApp()}catch(err){authError(err.message)}finally{button.disabled=false}}
  async function logout(){try{await api('/v1/storefront/auth/logout',{method:'POST'})}catch{}state.account=null;state.csrf='';$('#app').hidden=true;$('#authScreen').hidden=false;setLocked(true);showAuthTab('login')}
  function enterApp(){$('#authScreen').hidden=true;$('#app').hidden=false;setLocked(false);updateAccountUI();loadCatalog(false)}
  async function boot(){bind();try{const ok=await refreshAccount();if(ok)enterApp();else{$('#authScreen').hidden=false;setLocked(true)}}catch(e){authError(e.message)}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
  function bind(){
    $$('.auth-tab').forEach(b=>b.onclick=()=>showAuthTab(b.dataset.auth));$('#loginForm').onsubmit=submitLogin;$('#signupForm').onsubmit=submitSignup;$$('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.togglePassword);i.type=i.type==='password'?'text':'password'});$('#forgotPassword').onclick=()=>authError('استخدم بيانات الدعم بعد فتح الحساب لاستعادة كلمة المرور.');
    $('#menuButton').onclick=openDrawer;$('#quickMenu').onclick=openDrawer;$('#overlay').onclick=closeLayers;$$('[data-close]').forEach(b=>b.onclick=closeLayers);$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
    $('#searchInput').oninput=e=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>{state.query=e.target.value.trim();loadCatalog(false)},350)};$('#allProducts').onclick=()=>selectCategory('');$('#loadMore').onclick=()=>{state.page++;loadCatalog(true)};
    for(const id of ['depositButton','bottomDeposit','drawerDeposit'])$('#'+id).onclick=openDeposit;for(const id of ['logoutButton','drawerLogout'])$('#'+id).onclick=logout;
    addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('#installApp').hidden=false});$('#installApp').onclick=async()=>{if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('#installApp').hidden=true}};
    let touchX=0;$('#hero').addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});$('#hero').addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-touchX;if(Math.abs(delta)>45)goSlide(state.slide+(delta>0?-1:1),true)},{passive:true});
  }
  boot();
  </script>
</body>
</html>'''
