"""Owner-only administration interface for Uchiha Store."""

ADMIN_HTML = r'''<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#080b12">
  <title>إدارة Uchiha Store</title>
  <style>
    :root{--bg:#070910;--panel:#10141d;--panel2:#171c27;--panel3:#1d2431;--text:#f3f7ff;--muted:#929cad;--line:rgba(255,255,255,.085);--primary:#18d8c5;--secondary:#2d8cff;--accent:#8b5cf6;--danger:#ff6881;--gold:#f5c451;--shadow:0 24px 75px rgba(0,0,0,.45)}
    *{box-sizing:border-box}html{background:var(--bg)}body{margin:0;min-height:100vh;background:radial-gradient(circle at 85% -8%,rgba(24,216,197,.11),transparent 28%),var(--bg);color:var(--text);font-family:Tahoma,"Segoe UI",Arial,sans-serif}button,input,select,textarea{font:inherit}button{color:inherit}a{color:inherit;text-decoration:none}[hidden]{display:none!important}:focus-visible{outline:2px solid var(--primary);outline-offset:2px}.icon{width:22px;height:22px;display:block;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
    .layout{min-height:100vh;display:grid;grid-template-columns:260px minmax(0,1fr)}.sidebar{position:sticky;top:0;height:100vh;border-left:1px solid var(--line);background:rgba(9,12,19,.94);backdrop-filter:blur(18px);display:flex;flex-direction:column}.side-brand{display:flex;align-items:center;gap:12px;height:82px;padding:0 18px;border-bottom:1px solid var(--line)}.side-brand img{width:48px;height:48px;border-radius:16px}.side-brand b{display:block;font-size:14px}.side-brand small{display:block;margin-top:4px;color:var(--muted);font-size:9px;letter-spacing:1px}.nav{padding:14px 10px;overflow:auto}.nav-btn{width:100%;height:48px;display:flex;align-items:center;gap:12px;padding:0 13px;border:0;border-radius:14px;background:none;color:#aeb6c5;cursor:pointer;text-align:right}.nav-btn:hover,.nav-btn.active{background:var(--panel2);color:var(--primary)}.nav-btn .icon{width:20px}.side-foot{margin-top:auto;padding:14px;border-top:1px solid var(--line)}
    .main{min-width:0}.top{position:sticky;top:0;z-index:20;height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 24px;border-bottom:1px solid var(--line);background:rgba(7,9,16,.84);backdrop-filter:blur(18px)}.top h1{margin:0;font-size:18px}.top-actions{display:flex;gap:8px}.content{width:min(1280px,calc(100% - 38px));margin:24px auto 50px}.view{display:none;animation:in .2s ease}.view.active{display:block}@keyframes in{from{opacity:.2;transform:translateY(5px)}to{opacity:1;transform:none}}
    .cards{display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.stat{min-height:122px;padding:17px;border:1px solid var(--line);border-radius:19px;background:linear-gradient(145deg,var(--panel2),var(--panel));position:relative;overflow:hidden}.stat:after{content:"";position:absolute;width:75px;height:75px;left:-25px;bottom:-30px;border:14px solid rgba(255,255,255,.025);border-radius:50%}.stat span{display:block;color:var(--muted);font-size:10px}.stat strong{display:block;margin-top:15px;font-size:23px}.stat i{display:block;width:7px;height:7px;margin-bottom:10px;border-radius:50%;background:var(--stat,var(--primary));box-shadow:0 0 15px var(--stat,var(--primary))}
    .section{margin-top:18px;padding:20px;border:1px solid var(--line);border-radius:21px;background:var(--panel)}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:17px}.section-head h2{margin:0;font-size:17px}.section-head p{margin:5px 0 0;color:var(--muted);font-size:10px}.actions{display:flex;gap:8px;flex-wrap:wrap}.primary,.secondary,.danger,.ghost{min-height:43px;padding:0 15px;border-radius:13px;font-weight:900;cursor:pointer}.primary{border:0;background:linear-gradient(135deg,var(--primary),var(--secondary));color:#05100f}.secondary{border:1px solid rgba(45,140,255,.25);background:rgba(45,140,255,.08);color:#acd2ff}.danger{border:1px solid rgba(255,104,129,.25);background:rgba(255,104,129,.07);color:#ffadba}.ghost{border:1px solid var(--line);background:var(--panel2);color:var(--text)}.small{min-height:34px;padding:0 10px;font-size:9px}.wide{width:100%}button:disabled{opacity:.5;cursor:wait}
    .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.field{margin-bottom:12px}.field label{display:block;margin-bottom:7px;color:#d7ddea;font-size:10px;font-weight:900}.input,.select,.textarea{width:100%;min-height:47px;padding:0 13px;border:1px solid var(--line);border-radius:14px;background:var(--panel2);color:var(--text);outline:0}.textarea{min-height:95px;padding-top:12px;resize:vertical}.input:focus,.select:focus,.textarea:focus{border-color:rgba(24,216,197,.4);box-shadow:0 0 0 4px rgba(24,216,197,.06)}.check{display:flex;align-items:center;gap:8px;font-size:10px}.check input{width:18px;height:18px;accent-color:var(--primary)}
    .table-wrap{overflow:auto;border:1px solid var(--line);border-radius:16px}.table{width:100%;border-collapse:collapse;min-width:780px}.table th,.table td{padding:12px 13px;border-bottom:1px solid var(--line);text-align:right;font-size:10px;vertical-align:middle}.table th{position:sticky;top:0;background:var(--panel2);color:var(--muted);font-size:9px}.table tr:last-child td{border-bottom:0}.table tr:hover td{background:rgba(255,255,255,.015)}.badge{display:inline-flex;padding:6px 8px;border-radius:99px;background:rgba(45,140,255,.1);color:#acd2ff;font-size:8px;font-weight:900}.badge.ok{background:rgba(24,216,197,.1);color:#a8fff6}.badge.wait{background:rgba(245,196,81,.1);color:#f5da91}.badge.bad{background:rgba(255,104,129,.1);color:#ffabba}
    .banner-list,.category-list,.method-list{display:grid;gap:12px}.banner-item{display:grid;grid-template-columns:210px 1fr auto;gap:15px;align-items:center;padding:13px;border:1px solid var(--line);border-radius:17px;background:var(--panel2)}.banner-item img{width:210px;aspect-ratio:15/6;object-fit:cover;border-radius:13px}.banner-item h3{margin:0 0 7px;font-size:13px}.banner-item p{margin:0;color:var(--muted);font-size:9px;line-height:1.7}.banner-item .actions{flex-direction:column}
    .editor{padding:17px;border:1px solid rgba(24,216,197,.16);border-radius:17px;background:rgba(24,216,197,.025);margin-bottom:14px}.editor h3{margin:0 0 14px;font-size:14px}.image-preview{width:100%;max-height:230px;object-fit:cover;border:1px solid var(--line);border-radius:14px;background:var(--panel2);margin-bottom:12px}
    .category-row,.method-row{display:grid;grid-template-columns:70px minmax(160px,1fr) 130px 115px auto;gap:10px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:16px;background:var(--panel2)}.category-row img{width:65px;height:65px;object-fit:cover;border-radius:13px}.category-row b,.method-row b{font-size:11px}.category-row small,.method-row small{display:block;margin-top:5px;color:var(--muted);font-size:8px}.method-row{grid-template-columns:56px minmax(180px,1.3fr) 120px 120px auto}.method-icon{width:50px;height:50px;display:grid;place-items:center;border-radius:14px;background:rgba(24,216,197,.07);font-size:19px}.filter{display:flex;gap:9px;margin-bottom:14px}.filter .input{flex:1}
    .modal-overlay{position:fixed;inset:0;z-index:80;display:grid;place-items:center;padding:14px;background:rgba(0,0,0,.72);backdrop-filter:blur(5px);opacity:0;pointer-events:none;transition:.2s}.modal-overlay.show{opacity:1;pointer-events:auto}.modal{width:min(700px,100%);max-height:90vh;overflow:auto;padding:20px;border:1px solid var(--line);border-radius:21px;background:#0d1119;box-shadow:var(--shadow)}.modal-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:17px}.modal-head h2{margin:0;font-size:17px}.close{width:38px;height:38px;border:1px solid var(--line);border-radius:12px;background:var(--panel2);cursor:pointer}
    .login-screen{position:fixed;z-index:200;inset:0;display:grid;place-items:center;padding:16px;background:radial-gradient(circle at 50% 20%,rgba(24,216,197,.1),transparent 28%),#070910}.login-card{width:min(460px,100%);padding:28px;border:1px solid var(--line);border-radius:24px;background:var(--panel);box-shadow:var(--shadow)}.login-brand{text-align:center;margin-bottom:22px}.login-brand img{width:70px;margin:0 auto 12px}.login-brand h1{margin:0;font-size:22px}.login-brand p{margin:7px 0 0;color:var(--muted);font-size:10px}.login-error{display:none;margin-bottom:12px;padding:11px;border:1px solid rgba(255,104,129,.22);border-radius:12px;color:#ffb0be;background:rgba(255,104,129,.06);font-size:10px}.login-error.show{display:block}
    .toast{position:fixed;z-index:250;right:50%;bottom:22px;max-width:min(440px,calc(100% - 24px));padding:12px 16px;border:1px solid rgba(24,216,197,.2);border-radius:13px;background:#1a202b;box-shadow:var(--shadow);font-size:10px;opacity:0;pointer-events:none;transform:translate(50%,12px);transition:.2s}.toast.show{opacity:1;transform:translate(50%,0)}.toast.error{border-color:rgba(255,104,129,.3)}.empty{padding:32px;border:1px dashed var(--line);border-radius:15px;text-align:center;color:var(--muted);font-size:10px}.loading{color:var(--muted);padding:20px;text-align:center}
    .mobile-menu{display:none;width:42px;height:42px;border:1px solid var(--line);border-radius:13px;background:var(--panel2)}
    @media(max-width:1120px){.cards{grid-template-columns:repeat(3,1fr)}.category-row{grid-template-columns:65px 1fr 110px auto}.category-row .category-parent{display:none}.method-row{grid-template-columns:50px 1fr 110px auto}.method-row .method-range{display:none}}
    @media(max-width:820px){.layout{display:block}.sidebar{position:fixed;z-index:55;right:0;top:0;width:min(290px,88vw);transform:translateX(103%);transition:.25s}.sidebar.show{transform:none}.top{padding:0 14px}.mobile-menu{display:grid;place-items:center}.content{width:calc(100% - 22px);margin-top:14px}.grid2,.grid3{grid-template-columns:1fr}.banner-item{grid-template-columns:120px 1fr}.banner-item img{width:120px}.banner-item .actions{grid-column:1/-1;flex-direction:row}.category-row{grid-template-columns:58px 1fr auto}.category-row .category-sort{display:none}.method-row{grid-template-columns:48px 1fr auto}.method-row .method-currency{display:none}}
    @media(max-width:520px){.cards{grid-template-columns:repeat(2,1fr)}.stat{min-height:105px}.stat strong{font-size:19px}.section{padding:14px}.banner-item{grid-template-columns:1fr}.banner-item img{width:100%}.category-row{grid-template-columns:50px 1fr}.category-row>button{grid-column:1/-1}.method-row{grid-template-columns:45px 1fr}.method-row>button{grid-column:1/-1}.top h1{font-size:14px}}
  </style>
</head>
<body>
  <div class="layout" id="adminApp" hidden>
    <aside class="sidebar" id="sidebar">
      <div class="side-brand"><img src="/app-icon.svg" alt=""><div><b>Uchiha Store</b><small>OWNER PANEL</small></div></div>
      <nav class="nav">
        <button class="nav-btn active" data-view="dashboard">⌂ لوحة التحكم</button>
        <button class="nav-btn" data-view="appearance">◈ الهوية والصور</button>
        <button class="nav-btn" data-view="categories">▦ الأقسام</button>
        <button class="nav-btn" data-view="payments">◇ طرق الدفع</button>
        <button class="nav-btn" data-view="deposits">＋ طلبات الشحن</button>
        <button class="nav-btn" data-view="orders">▣ الطلبات</button>
        <button class="nav-btn" data-view="customers">♙ العملاء والأرصدة</button>
      </nav>
      <div class="side-foot"><a class="ghost wide" style="display:grid;place-items:center" href="/" target="_blank">فتح المتجر</a><button class="danger wide" id="adminLogout" style="margin-top:8px">تسجيل الخروج</button></div>
    </aside>
    <main class="main">
      <header class="top"><div style="display:flex;align-items:center;gap:10px"><button class="mobile-menu" id="mobileMenu">☰</button><h1 id="viewTitle">لوحة التحكم</h1></div><div class="top-actions"><button class="secondary" id="quickSync">تحديث JS4Card</button></div></header>
      <div class="content">
        <section class="view active" data-page="dashboard"><div class="cards" id="stats"><div class="loading">جاري تحميل الإحصائيات...</div></div><div class="section"><div class="section-head"><div><h2>تشغيل المتجر</h2><p>اختصارات الإدارة الأساسية</p></div></div><div class="actions"><button class="primary" data-view="appearance">تعديل الصور والهوية</button><button class="secondary" data-view="categories">تنظيم الأقسام</button><button class="ghost" data-view="deposits">مراجعة الشحن</button><button class="ghost" data-view="orders">متابعة الطلبات</button><button class="danger" id="fullSync">مزامنة JS4Card كاملة</button></div></div></section>
        <section class="view" data-page="appearance"><div class="section"><div class="section-head"><div><h2>بيانات المتجر والدعم</h2><p>كل هذه القيم تظهر للعميل مباشرة</p></div><button class="primary" id="saveSettings">حفظ التعديلات</button></div><div id="settingsForm" class="loading">جاري تحميل الإعدادات...</div></div><div class="section"><div class="section-head"><div><h2>صور السلايدر</h2><p>يمكنك الرفع والتعديل والترتيب والإخفاء</p></div><button class="primary" id="addBanner">إضافة صورة</button></div><div id="bannerEditor"></div><div class="banner-list" id="bannerList"><div class="loading">جاري تحميل الصور...</div></div></div></section>
        <section class="view" data-page="categories"><div class="section"><div class="section-head"><div><h2>صور وترتيب الأقسام</h2><p>الأقسام والمنتجات مصدرها JS4Card، وأنت تتحكم بما يظهر</p></div><button class="secondary" id="categorySync">تحديث سريع</button></div><div class="filter"><input class="input" id="categorySearch" placeholder="ابحث باسم القسم..."><select class="select" id="categoryFilter" style="max-width:180px"><option value="root">الرئيسية فقط</option><option value="all">جميع الأقسام</option><option value="visible">الظاهرة</option><option value="hidden">المخفية</option></select></div><div class="category-list" id="categoryList"><div class="loading">جاري تحميل الأقسام...</div></div></div></section>
        <section class="view" data-page="payments"><div class="section"><div class="section-head"><div><h2>طرق الدفع</h2><p>التحويل اليدوي والبوابات الإلكترونية المفعلة</p></div></div><div class="method-list" id="methodList"><div class="loading">جاري تحميل طرق الدفع...</div></div></div></section>
        <section class="view" data-page="deposits"><div class="section"><div class="section-head"><div><h2>طلبات شحن الرصيد</h2><p>اعتماد أو رفض الإثباتات اليدوية</p></div><button class="ghost" id="reloadDeposits">تحديث</button></div><div id="depositTable"><div class="loading">جاري تحميل الطلبات...</div></div></div></section>
        <section class="view" data-page="orders"><div class="section"><div class="section-head"><div><h2>طلبات المنتجات</h2><p>حالة طلبات الموقع ومزود JS4Card</p></div><button class="ghost" id="reloadOrders">تحديث</button></div><div id="orderTable"><div class="loading">جاري تحميل الطلبات...</div></div></div></section>
        <section class="view" data-page="customers"><div class="section"><div class="section-head"><div><h2>العملاء والأرصدة</h2><p>الرصيد هنا هو نفسه في الموقع والبوت</p></div><button class="ghost" id="reloadCustomers">تحديث</button></div><div id="customerTable"><div class="loading">جاري تحميل العملاء...</div></div></div></section>
      </div>
    </main>
  </div>

  <section class="login-screen" id="loginScreen"><form class="login-card" id="adminLoginForm"><div class="login-brand"><img src="/app-icon.svg" alt=""><h1>إدارة Uchiha Store</h1><p>هذه الصفحة خاصة بصاحب المتجر فقط</p></div><div class="login-error" id="loginError"></div><div class="field"><label>اسم مدير المتجر</label><input class="input" id="adminUsername" autocomplete="username" required></div><div class="field"><label>كلمة المرور</label><input class="input" id="adminPassword" type="password" autocomplete="current-password" required></div><button class="primary wide" type="submit">تسجيل الدخول</button></form></section>
  <div class="modal-overlay" id="modalOverlay"><div class="modal"><div class="modal-head"><h2 id="modalTitle">تعديل</h2><button class="close" id="closeModal">✕</button></div><div id="modalBody"></div></div></div>
  <div class="toast" id="toast"></div>
  <script>
  'use strict';
  const state={csrf:'',settings:{},banners:[],categories:[],methods:[],view:'dashboard'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function message(data,f='حدث خطأ'){const d=data?.detail;return typeof d==='string'?d:(d?.message||data?.message||f)}
  async function api(url,opt={}){const headers={Accept:'application/json',...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})};if(state.csrf&&opt.method&&opt.method!=='GET')headers['X-CSRF-Token']=state.csrf;const r=await fetch(url,{credentials:'same-origin',...opt,headers});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(message(d));e.status=r.status;throw e}return d}
  function toast(text,error=false){const e=$('#toast');e.textContent=text;e.classList.toggle('error',error);e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),3000)}
  function statusBadge(value){const v=String(value||'').toLowerCase(),c=/approve|complete|success/.test(v)?'ok':/reject|cancel|fail/.test(v)?'bad':'wait';return `<span class="badge ${c}">${esc(value||'pending')}</span>`}
  function money(v){return `$ ${Number(v||0).toFixed(2)}`}
  function showView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.page===name));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const names={dashboard:'لوحة التحكم',appearance:'الهوية والصور',categories:'الأقسام',payments:'طرق الدفع',deposits:'طلبات الشحن',orders:'الطلبات',customers:'العملاء والأرصدة'};$('#viewTitle').textContent=names[name]||'الإدارة';$('#sidebar').classList.remove('show');if(name==='dashboard')loadDashboard();if(name==='appearance')loadAppearance();if(name==='categories')loadCategories();if(name==='payments')loadMethods();if(name==='deposits')loadDeposits();if(name==='orders')loadOrders();if(name==='customers')loadCustomers()}
  function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalOverlay').classList.add('show')}
  function closeModal(){$('#modalOverlay').classList.remove('show')}
  async function fileData(file){if(!file)return'';if(file.size>3*1024*1024)throw new Error('الصورة أكبر من 3 ميغابايت');return await new Promise((ok,bad)=>{const r=new FileReader;r.onload=()=>ok(String(r.result));r.onerror=bad;r.readAsDataURL(file)})}
  async function loadDashboard(){try{const d=await api('/v1/storefront/admin/dashboard');const stats=[['الحسابات',d.accounts,'#18d8c5'],['مرتبطة بالبوت',d.linked_accounts,'#2d8cff'],['المنتجات',d.products,'#8b5cf6'],['الطلبات',d.orders,'#f5c451'],['المبيعات',money(d.sales),'#18d8c5'],['شحن بانتظارك',d.pending_deposits,'#ff9d6c']];$('#stats').innerHTML=stats.map(x=>`<div class="stat" style="--stat:${x[2]}"><i></i><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}catch(e){toast(e.message,true)}}
  async function loadAppearance(){await Promise.all([loadSettings(),loadBanners()])}
  async function loadSettings(){try{state.settings=await api('/v1/storefront/admin/settings');const s=state.settings;$('#settingsForm').innerHTML=`<div class="grid2"><div class="field"><label>اسم المتجر</label><input class="input" data-setting="store_name" value="${esc(s.store_name)}"></div><div class="field"><label>الجملة التعريفية</label><input class="input" data-setting="tagline" value="${esc(s.tagline)}"></div><div class="field" style="grid-column:1/-1"><label>شريط الإعلان</label><input class="input" data-setting="announcement" value="${esc(s.announcement)}"></div><div class="field"><label>حساب دعم تيليجرام بدون @</label><input class="input" data-setting="support_telegram" value="${esc(s.support_telegram)}"></div><div class="field"><label>رقم واتساب الدولي</label><input class="input" data-setting="support_whatsapp" value="${esc(s.support_whatsapp)}"></div><div class="field"><label>بريد الدعم</label><input class="input" data-setting="support_email" value="${esc(s.support_email)}"></div><div class="field"><label>أوقات الدعم</label><input class="input" data-setting="support_hours" value="${esc(s.support_hours)}"></div><div class="field"><label>مدة انتقال السلايدر بالميلي ثانية</label><input class="input" type="number" min="2500" max="12000" data-setting="hero_interval_ms" value="${esc(s.hero_interval_ms)}"></div><div class="field"><label>رمز العملة</label><input class="input" data-setting="currency_symbol" value="${esc(s.currency_symbol)}"></div></div><div class="grid3"><div class="field"><label>اللون الأساسي</label><input class="input" type="color" data-setting="primary_color" value="${esc(s.primary_color)}"></div><div class="field"><label>اللون الثانوي</label><input class="input" type="color" data-setting="secondary_color" value="${esc(s.secondary_color)}"></div><div class="field"><label>لون اللمسات</label><input class="input" type="color" data-setting="accent_color" value="${esc(s.accent_color)}"></div></div>`}catch(e){toast(e.message,true)}}
  async function saveSettings(){const payload={};$$('[data-setting]').forEach(i=>payload[i.dataset.setting]=i.value.trim());try{await api('/v1/storefront/admin/settings',{method:'PUT',body:JSON.stringify(payload)});toast('تم حفظ بيانات المتجر والدعم')}catch(e){toast(e.message,true)}}
  async function loadBanners(){try{const d=await api('/v1/storefront/admin/banners');state.banners=d.items||[];renderBanners()}catch(e){toast(e.message,true)}}
  function renderBanners(){const box=$('#bannerList');box.innerHTML=state.banners.length?state.banners.map(b=>`<article class="banner-item"><img src="${esc(b.image_url)}" alt=""><div><h3>${esc(b.title)}</h3><p>${esc(b.subtitle)}</p><p>الترتيب: ${b.sort_order} • ${b.enabled?'ظاهر':'مخفي'}</p></div><div class="actions"><button class="secondary small" data-edit-banner="${b.id}">تعديل</button><button class="danger small" data-delete-banner="${b.id}">حذف</button></div></article>`).join(''):'<div class="empty">لا توجد صور سلايدر.</div>';$$('[data-edit-banner]').forEach(b=>b.onclick=()=>editBanner(Number(b.dataset.editBanner)));$$('[data-delete-banner]').forEach(b=>b.onclick=()=>deleteBanner(Number(b.dataset.deleteBanner)))}
  function editBanner(id=0){const b=state.banners.find(x=>x.id===id)||{id:0,title:'',subtitle:'',cta_label:'تسوّق الآن',cta_target:'#products',accent:'#18d8c5',art_variant:'ninja',enabled:1,sort_order:(state.banners.length+1)*10};$('#bannerEditor').innerHTML=`<div class="editor"><h3>${id?'تعديل الصورة':'إضافة صورة جديدة'}</h3>${id?`<img class="image-preview" src="${esc(b.image_url)}" alt="">`:''}<div class="grid2"><div class="field"><label>العنوان</label><input class="input" id="bannerTitle" value="${esc(b.title)}"></div><div class="field"><label>النص القصير</label><input class="input" id="bannerSubtitle" value="${esc(b.subtitle)}"></div><div class="field"><label>نص الزر</label><input class="input" id="bannerCta" value="${esc(b.cta_label)}"></div><div class="field"><label>وجهة الزر</label><select class="select" id="bannerTarget"><option value="#products">المنتجات</option><option value="#categories">الأقسام</option><option value="#bot-link">ربط البوت</option></select></div><div class="field"><label>لون الصورة</label><input class="input" id="bannerAccent" type="color" value="${esc(b.accent)}"></div><div class="field"><label>الترتيب</label><input class="input" id="bannerSort" type="number" value="${b.sort_order}"></div><div class="field"><label>رفع صورة جديدة (اختياري)</label><input class="input" id="bannerImage" type="file" accept="image/jpeg,image/png,image/webp,image/gif" style="padding:10px"></div><label class="check"><input id="bannerEnabled" type="checkbox" ${b.enabled?'checked':''}>إظهار الصورة</label></div><div class="actions"><button class="primary" id="saveBannerEditor">حفظ الصورة</button><button class="ghost" id="cancelBannerEditor">إلغاء</button></div></div>`;$('#bannerTarget').value=b.cta_target||'#products';$('#saveBannerEditor').onclick=()=>saveBanner(id,b.art_variant);$('#cancelBannerEditor').onclick=()=>$('#bannerEditor').innerHTML='';$('#bannerEditor').scrollIntoView({behavior:'smooth'})}
  async function saveBanner(id,variant){const button=$('#saveBannerEditor');button.disabled=true;try{const image=await fileData($('#bannerImage').files[0]);const payload={id,title:$('#bannerTitle').value.trim(),subtitle:$('#bannerSubtitle').value.trim(),cta_label:$('#bannerCta').value.trim(),cta_target:$('#bannerTarget').value,accent:$('#bannerAccent').value,art_variant:variant||'ninja',enabled:$('#bannerEnabled').checked,sort_order:Number($('#bannerSort').value||0),image};await api('/v1/storefront/admin/banners',{method:'POST',body:JSON.stringify(payload)});$('#bannerEditor').innerHTML='';toast('تم حفظ صورة السلايدر');await loadBanners()}catch(e){toast(e.message,true)}finally{button.disabled=false}}
  async function deleteBanner(id){if(!confirm('حذف هذه الصورة من السلايدر؟'))return;try{await api('/v1/storefront/admin/banners/'+id,{method:'DELETE'});toast('تم حذف الصورة');loadBanners()}catch(e){toast(e.message,true)}}
  async function loadCategories(){try{const d=await api('/v1/storefront/admin/categories');state.categories=d.items||[];renderCategories()}catch(e){toast(e.message,true)}}
  function renderCategories(){const q=$('#categorySearch').value.trim().toLowerCase(),filter=$('#categoryFilter').value;let rows=state.categories.filter(c=>!q||String(c.display_name||c.name).toLowerCase().includes(q));if(filter==='root')rows=rows.filter(c=>!c.parent_id);if(filter==='visible')rows=rows.filter(c=>!c.is_hidden);if(filter==='hidden')rows=rows.filter(c=>c.is_hidden);$('#categoryList').innerHTML=rows.length?rows.slice(0,250).map(c=>`<article class="category-row"><img src="${esc(c.image_url)}" alt=""><div><b>${esc(c.display_name||c.name)}</b><small>${c.product_count} منتج • #${c.id}${c.is_hidden?' • مخفي':''}</small></div><div class="category-parent"><small>القسم الأب</small><b>#${c.parent_id||'رئيسي'}</b></div><div class="category-sort"><small>الترتيب</small><b>${c.sort_order}</b></div><button class="secondary small" data-edit-category="${c.id}">تعديل</button></article>`).join(''):'<div class="empty">لا توجد أقسام مطابقة.</div>';$$('[data-edit-category]').forEach(b=>b.onclick=()=>editCategory(Number(b.dataset.editCategory)))}
  function editCategory(id){const c=state.categories.find(x=>x.id===id);if(!c)return;openModal('تعديل القسم',`<img class="image-preview" src="${esc(c.image_url)}" alt=""><div class="field"><label>الاسم الظاهر للعميل</label><input class="input" id="catName" value="${esc(c.display_name||c.name)}"></div><div class="grid2"><div class="field"><label>ترتيب الظهور</label><input class="input" id="catSort" type="number" value="${c.sort_order}"></div><div class="field"><label>لون القسم</label><input class="input" id="catAccent" type="color" value="${esc(c.accent||'#18d8c5')}"></div></div><div class="field"><label>صورة القسم (اختياري)</label><input class="input" id="catImage" type="file" accept="image/jpeg,image/png,image/webp,image/gif" style="padding:10px"></div><label class="check"><input id="catHidden" type="checkbox" ${c.is_hidden?'checked':''}>إخفاء القسم من المتجر</label><button class="primary wide" id="saveCategory" style="margin-top:16px">حفظ القسم</button>`);$('#saveCategory').onclick=()=>saveCategory(id)}
  async function saveCategory(id){const b=$('#saveCategory');b.disabled=true;try{const image=await fileData($('#catImage').files[0]);await api('/v1/storefront/admin/categories/'+id,{method:'PUT',body:JSON.stringify({display_name:$('#catName').value.trim(),sort_order:Number($('#catSort').value||0),is_hidden:$('#catHidden').checked,accent:$('#catAccent').value,image})});closeModal();toast('تم حفظ القسم');loadCategories()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
  async function loadMethods(){try{const d=await api('/v1/storefront/admin/payment-methods');state.methods=d.items||[];$('#methodList').innerHTML=state.methods.length?state.methods.map(m=>`<article class="method-row"><div class="method-icon">${esc(m.icon||'◇')}</div><div><b>${esc(m.name)}</b><small>${esc(m.details||'')}</small></div><div class="method-currency"><small>العملة</small><b>${esc(m.currency||'USD')}</b></div><div class="method-range"><small>الحدود</small><b>${m.min_amount||0} - ${m.max_amount||'∞'}</b></div><button class="secondary small" data-edit-method="${m.id}">تعديل</button></article>`).join(''):'<div class="empty">لا توجد طرق دفع بعد.</div>';$$('[data-edit-method]').forEach(b=>b.onclick=()=>editMethod(Number(b.dataset.editMethod)))}catch(e){toast(e.message,true)}}
  function editMethod(id){const m=state.methods.find(x=>x.id===id);if(!m)return;openModal('تعديل طريقة الدفع',`<div class="grid2"><div class="field"><label>الاسم</label><input class="input" id="methodName" value="${esc(m.name)}"></div><div class="field"><label>العملة</label><input class="input" id="methodCurrency" value="${esc(m.currency||'USD')}"></div><div class="field" style="grid-column:1/-1"><label>التعليمات</label><textarea class="textarea" id="methodDetails">${esc(m.details||'')}</textarea></div><div class="field"><label>عنوان بيانات التحويل</label><input class="input" id="methodLabel" value="${esc(m.transfer_label||'')}"></div><div class="field"><label>رقم/عنوان التحويل</label><input class="input" id="methodValue" value="${esc(m.transfer_value||'')}"></div><div class="field"><label>الحد الأدنى</label><input class="input" id="methodMin" type="number" step="0.01" value="${m.min_amount||0}"></div><div class="field"><label>الحد الأعلى</label><input class="input" id="methodMax" type="number" step="0.01" value="${m.max_amount||0}"></div><div class="field"><label>معامل إضافة الرصيد</label><input class="input" id="methodRate" type="number" step="0.01" value="${m.credit_rate||1}"></div><div class="field"><label>رسم ثابت</label><input class="input" id="methodFixed" type="number" step="0.01" value="${m.fixed_fee||0}"></div><div class="field"><label>نسبة الرسم %</label><input class="input" id="methodPercent" type="number" step="0.01" value="${m.fee_percent||0}"></div><div class="field"><label>الترتيب</label><input class="input" id="methodSort" type="number" value="${m.sort_order||0}"></div></div><div class="actions"><label class="check"><input id="methodActive" type="checkbox" ${m.is_active?'checked':''}>مفعلة</label><label class="check"><input id="methodProof" type="checkbox" ${m.proof_required?'checked':''}>تتطلب إثباتًا</label></div><button class="primary wide" id="saveMethod" style="margin-top:16px">حفظ طريقة الدفع</button>`);$('#saveMethod').onclick=()=>saveMethod(id)}
  async function saveMethod(id){const payload={name:$('#methodName').value.trim(),currency:$('#methodCurrency').value.trim(),details:$('#methodDetails').value.trim(),transfer_label:$('#methodLabel').value.trim(),transfer_value:$('#methodValue').value.trim(),min_amount:Number($('#methodMin').value||0),max_amount:Number($('#methodMax').value||0),credit_rate:Number($('#methodRate').value||1),fixed_fee:Number($('#methodFixed').value||0),fee_percent:Number($('#methodPercent').value||0),sort_order:Number($('#methodSort').value||0),is_active:$('#methodActive').checked,proof_required:$('#methodProof').checked};try{await api('/v1/storefront/admin/payment-methods/'+id,{method:'PUT',body:JSON.stringify(payload)});closeModal();toast('تم حفظ طريقة الدفع');loadMethods()}catch(e){toast(e.message,true)}}
  async function loadDeposits(){try{const d=await api('/v1/storefront/admin/deposits');const rows=d.items||[];$('#depositTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>العميل</th><th>الطريقة</th><th>المدفوع</th><th>الرصيد</th><th>الحالة</th><th>الإثبات</th><th>الإجراء</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.username||x.user_id)}</td><td>${esc(x.payment_method)}</td><td>${money(x.paid_amount)}</td><td>${money(x.credited_amount||x.amount)}</td><td>${statusBadge(x.status)}</td><td>${x.proof_url?`<a class="secondary small" href="${esc(x.proof_url)}" target="_blank">عرض</a>`:esc(x.transaction_reference||'—')}</td><td>${x.status==='pending'?`<button class="primary small" data-dep-approve="${x.id}">اعتماد</button> <button class="danger small" data-dep-reject="${x.id}">رفض</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد طلبات شحن.</div>';$$('[data-dep-approve]').forEach(b=>b.onclick=()=>reviewDeposit(Number(b.dataset.depApprove),'approve'));$$('[data-dep-reject]').forEach(b=>b.onclick=()=>reviewDeposit(Number(b.dataset.depReject),'reject'))}catch(e){toast(e.message,true)}}
  async function reviewDeposit(id,decision){const note=prompt(decision==='approve'?'ملاحظة الاعتماد (اختيارية)':'سبب الرفض (اختياري)')||'';if(!confirm(decision==='approve'?'تأكيد إضافة الرصيد للعميل؟':'تأكيد رفض الطلب؟'))return;try{await api(`/v1/storefront/admin/deposits/${id}/review`,{method:'POST',body:JSON.stringify({decision,note})});toast(decision==='approve'?'تم اعتماد الرصيد':'تم رفض الطلب');loadDeposits()}catch(e){toast(e.message,true)}}
  async function loadOrders(){try{const d=await api('/v1/storefront/admin/orders');const rows=d.items||[];$('#orderTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>العميل</th><th>المنتج</th><th>المبلغ</th><th>الحالة</th><th>JS4Card</th><th>التاريخ</th></tr></thead><tbody>${rows.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.username||o.user_id)}<br><small>${esc(o.email||'')}</small></td><td>${esc(o.product_name)} × ${o.quantity}</td><td>${money(o.total_price)}</td><td>${statusBadge(o.status)}</td><td>${esc(o.api_status||o.api_order_id||'—')}</td><td>${esc(o.order_date)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد طلبات.</div>'}catch(e){toast(e.message,true)}}
  async function loadCustomers(){try{const d=await api('/v1/storefront/admin/accounts');const rows=d.items||[];$('#customerTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>اسم المستخدم</th><th>البريد</th><th>الهاتف</th><th>تيليجرام</th><th>الرصيد</th><th>الإجراء</th></tr></thead><tbody>${rows.map(a=>`<tr><td>#${a.id}</td><td>${esc(a.username)}</td><td>${esc(a.email)}</td><td>${esc(a.phone)}</td><td>${a.telegram_id?`<span class="badge ok">مرتبط</span>`:'غير مرتبط'}</td><td>${money(a.balance)}</td><td><button class="secondary small" data-balance="${a.id}">تعديل الرصيد</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد حسابات.</div>';$$('[data-balance]').forEach(b=>b.onclick=()=>adjustBalance(Number(b.dataset.balance)))}catch(e){toast(e.message,true)}}
  async function adjustBalance(id){const raw=prompt('أدخل مبلغًا موجبًا للإضافة أو سالبًا للخصم، مثال: 10 أو -5');if(raw===null)return;const amount=Number(raw);if(!amount){toast('المبلغ غير صحيح',true);return}const reason=prompt('سبب التعديل')||'تعديل من لوحة الإدارة';if(!confirm(`تأكيد تعديل الرصيد بمقدار ${amount}؟`))return;try{await api(`/v1/storefront/admin/accounts/${id}/balance`,{method:'POST',body:JSON.stringify({amount,reason})});toast('تم تعديل الرصيد');loadCustomers();loadDashboard()}catch(e){toast(e.message,true)}}
  async function sync(mode='quick'){const text=mode==='full'?'المزامنة الكاملة قد تستغرق وقتًا. هل تريد المتابعة؟':'تحديث المنتجات من JS4Card الآن؟';if(!confirm(text))return;toast('بدأت مزامنة JS4Card...');try{const d=await api('/v1/storefront/admin/sync',{method:'POST',body:JSON.stringify({mode})});toast(d.status==='success'||d.status==='skipped_recent'?'اكتملت المزامنة':'انتهت المزامنة: '+(d.status||''));if(state.view==='categories')loadCategories();loadDashboard()}catch(e){toast(e.message,true)}}
  async function login(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{const d=await api('/v1/storefront/admin/auth/login',{method:'POST',body:JSON.stringify({username:$('#adminUsername').value.trim(),password:$('#adminPassword').value})});state.csrf=d.csrf_token;$('#loginScreen').hidden=true;$('#adminApp').hidden=false;loadDashboard()}catch(err){const el=$('#loginError');el.textContent=err.message;el.classList.add('show')}finally{b.disabled=false}}
  async function logout(){await fetch('/v1/storefront/auth/logout',{method:'POST',credentials:'same-origin'}).catch(()=>{});location.reload()}
  async function boot(){bind();try{const d=await api('/v1/storefront/admin/me');state.csrf=d.csrf_token;$('#loginScreen').hidden=true;$('#adminApp').hidden=false;loadDashboard()}catch{$('#loginScreen').hidden=false}}
  function bind(){$$('.nav-btn,[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#adminLoginForm').onsubmit=login;$('#adminLogout').onclick=logout;$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('show');$('#closeModal').onclick=closeModal;$('#modalOverlay').onclick=e=>{if(e.target===e.currentTarget)closeModal()};$('#saveSettings').onclick=saveSettings;$('#addBanner').onclick=()=>editBanner();$('#categorySearch').oninput=renderCategories;$('#categoryFilter').onchange=renderCategories;$('#reloadDeposits').onclick=loadDeposits;$('#reloadOrders').onclick=loadOrders;$('#reloadCustomers').onclick=loadCustomers;$('#quickSync').onclick=()=>sync('quick');$('#categorySync').onclick=()=>sync('quick');$('#fullSync').onclick=()=>sync('full')}
  boot();
  </script>
</body>
</html>'''
