"""Admin UI patch for recursive category tree management."""

from __future__ import annotations


CATEGORY_ADMIN_CSS = r"""
    .category-row.tree-row{grid-template-columns:72px minmax(220px,1.5fr) minmax(130px,.7fr) 100px auto}.category-tree-name{padding-inline-start:calc(var(--depth,0) * 18px);position:relative}.category-tree-name:before{content:"";position:absolute;right:calc(var(--depth,0) * 18px - 9px);top:50%;width:9px;border-top:1px solid rgba(255,255,255,.12)}.category-path{color:var(--muted);font-size:8px}.category-editor-preview{display:grid;grid-template-columns:1fr 90px;gap:10px;margin-bottom:13px}.category-editor-preview img{width:100%;height:120px;object-fit:cover;border-radius:14px;background:#09090e}.category-editor-preview img:last-child{height:90px;object-fit:contain}.category-editor-media{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.category-delete-note{margin-top:12px;color:var(--muted);font-size:9px;line-height:1.7}
    @media(max-width:840px){.category-row.tree-row{grid-template-columns:60px 1fr auto}.category-row.tree-row .category-parent,.category-row.tree-row .category-sort{display:none}.category-editor-media{grid-template-columns:1fr}}
"""

OLD_SECTION = '<section class="view" data-page="categories"><div class="section"><div class="section-head"><div><h2>صور وترتيب الأقسام</h2><p>الأقسام والمنتجات مصدرها JS4Card، وأنت تتحكم بما يظهر</p></div><button class="secondary" id="categorySync">تحديث سريع</button></div>'
NEW_SECTION = '<section class="view" data-page="categories"><div class="section"><div class="section-head"><div><h2>شجرة الأقسام والصور</h2><p>أنشئ أقسامًا رئيسية وفرعية وانقلها مثل ترتيب البوت</p></div><div class="actions"><button class="primary" id="addCategory">إضافة قسم</button><button class="secondary" id="categorySync">تحديث سريع</button></div></div>'

OLD_FUNCTIONS = r'''  async function loadCategories(){try{const d=await api('/v1/storefront/admin/categories');state.categories=d.items||[];renderCategories()}catch(e){toast(e.message,true)}}
  function renderCategories(){const q=$('#categorySearch').value.trim().toLowerCase(),filter=$('#categoryFilter').value;let rows=state.categories.filter(c=>!q||String(c.display_name||c.name).toLowerCase().includes(q));if(filter==='root')rows=rows.filter(c=>!c.parent_id);if(filter==='visible')rows=rows.filter(c=>!c.is_hidden);if(filter==='hidden')rows=rows.filter(c=>c.is_hidden);$('#categoryList').innerHTML=rows.length?rows.slice(0,250).map(c=>`<article class="category-row"><img src="${esc(c.image_url)}" alt=""><div><b>${esc(c.display_name||c.name)}</b><small>${c.product_count} منتج • #${c.id}${c.is_hidden?' • مخفي':''}</small></div><div class="category-parent"><small>القسم الأب</small><b>#${c.parent_id||'رئيسي'}</b></div><div class="category-sort"><small>الترتيب</small><b>${c.sort_order}</b></div><button class="secondary small" data-edit-category="${c.id}">تعديل</button></article>`).join(''):'<div class="empty">لا توجد أقسام مطابقة.</div>';$$('[data-edit-category]').forEach(b=>b.onclick=()=>editCategory(Number(b.dataset.editCategory)))}
  function editCategory(id){const c=state.categories.find(x=>x.id===id);if(!c)return;openModal('تعديل القسم',`<img class="image-preview" src="${esc(c.image_url)}" alt=""><div class="field"><label>الاسم الظاهر للعميل</label><input class="input" id="catName" value="${esc(c.display_name||c.name)}"></div><div class="grid2"><div class="field"><label>ترتيب الظهور</label><input class="input" id="catSort" type="number" value="${c.sort_order}"></div><div class="field"><label>لون القسم</label><input class="input" id="catAccent" type="color" value="${esc(c.accent||'#e4313f')}"></div></div><div class="field"><label>صورة القسم (اختياري)</label><input class="input" id="catImage" type="file" accept="image/jpeg,image/png,image/webp,image/gif" style="padding:10px"></div><label class="check"><input id="catHidden" type="checkbox" ${c.is_hidden?'checked':''}>إخفاء القسم من المتجر</label><button class="primary wide" id="saveCategory" style="margin-top:16px">حفظ القسم</button>`);$('#saveCategory').onclick=()=>saveCategory(id)}
  async function saveCategory(id){const b=$('#saveCategory');b.disabled=true;try{const image=await fileData($('#catImage').files[0]);await api('/v1/storefront/admin/categories/'+id,{method:'PUT',body:JSON.stringify({display_name:$('#catName').value.trim(),sort_order:Number($('#catSort').value||0),is_hidden:$('#catHidden').checked,accent:$('#catAccent').value,image})});closeModal();toast('تم حفظ القسم');loadCategories()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
'''

NEW_FUNCTIONS = r'''  async function loadCategories(){try{const d=await api('/v1/storefront/admin/category-tree');state.categories=d.items||[];renderCategories()}catch(e){toast(e.message,true)}}
  function categoryById(id){return state.categories.find(x=>Number(x.id)===Number(id))||null}
  function categoryLabel(c){return c?String(c.display_name||c.name||'قسم'):''}
  function categoryPathLabel(c){const parts=[],seen=new Set();let current=c;while(current&&!seen.has(current.id)){seen.add(current.id);parts.unshift(categoryLabel(current));current=categoryById(current.parent_id)}return parts.join(' / ')}
  function flatCategoryTree(){const byParent=new Map();for(const c of state.categories){const p=Number(c.parent_id||0);if(!byParent.has(p))byParent.set(p,[]);byParent.get(p).push(c)}for(const rows of byParent.values())rows.sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0)||categoryLabel(a).localeCompare(categoryLabel(b),'ar'));const out=[],walk=(parent,depth)=>{for(const c of byParent.get(parent)||[]){c._depth=depth;out.push(c);walk(Number(c.id),depth+1)}};walk(0,0);for(const c of state.categories)if(!out.includes(c)){c._depth=0;out.push(c)}return out}
  function renderCategories(){const q=$('#categorySearch').value.trim().toLowerCase(),filter=$('#categoryFilter').value;let rows=flatCategoryTree().filter(c=>!q||categoryPathLabel(c).toLowerCase().includes(q));if(filter==='root')rows=rows.filter(c=>!c.parent_id);if(filter==='visible')rows=rows.filter(c=>!c.is_hidden);if(filter==='hidden')rows=rows.filter(c=>c.is_hidden);$('#categoryList').innerHTML=rows.length?rows.slice(0,400).map(c=>`<article class="category-row tree-row" style="--depth:${Math.min(8,Number(c._depth||0))}"><img src="${esc(c.icon_url||c.image_url)}" alt=""><div class="category-tree-name"><b>${esc(categoryLabel(c))}</b><small>${c.child_count} أقسام داخلية • ${c.product_count} منتج • #${c.id}${c.is_hidden?' • مخفي':''}</small><div class="category-path">${esc(categoryPathLabel(c))}</div></div><div class="category-parent"><small>القسم الأب</small><b>${esc(categoryLabel(categoryById(c.parent_id))||'رئيسي')}</b></div><div class="category-sort"><small>الترتيب</small><b>${c.sort_order}</b></div><button class="secondary small" data-edit-category="${c.id}">تعديل</button></article>`).join(''):'<div class="empty">لا توجد أقسام مطابقة.</div>';$$('[data-edit-category]').forEach(b=>b.onclick=()=>editCategory(Number(b.dataset.editCategory)))}
  function categoryParentOptions(selected=0,exclude=0){return `<option value="0">قسم رئيسي</option>`+flatCategoryTree().filter(c=>Number(c.id)!==Number(exclude)).map(c=>`<option value="${c.id}" ${Number(c.id)===Number(selected)?'selected':''}>${'— '.repeat(Math.min(6,Number(c._depth||0)))}${esc(categoryLabel(c))}</option>`).join('')}
  function categoryEditor(c=null){const id=Number(c?.id||0);openModal(id?'تعديل القسم':'إضافة قسم جديد',`${id?`<div class="category-editor-preview"><img src="${esc(c.banner_url||c.image_url)}" alt=""><img src="${esc(c.icon_url||c.image_url)}" alt=""></div>`:''}<div class="field"><label>اسم القسم</label><input class="input" id="catName" value="${esc(c?categoryLabel(c):'')}"></div><div class="field"><label>وصف قصير</label><textarea class="textarea" id="catDescription" maxlength="500">${esc(c?.description||'')}</textarea></div><div class="grid2"><div class="field"><label>القسم الأب</label><select class="select" id="catParent">${categoryParentOptions(c?.parent_id||0,id)}</select></div><div class="field"><label>ترتيب الظهور</label><input class="input" id="catSort" type="number" value="${Number(c?.sort_order||0)}"></div><div class="field"><label>شارة اختيارية</label><input class="input" id="catBadge" maxlength="30" value="${esc(c?.badge||'')}" placeholder="جديد أو مميز"></div><div class="field"><label>لون القسم</label><input class="input" id="catAccent" type="color" value="${esc(c?.accent||'#e4313f')}"></div></div><div class="category-editor-media"><div class="field"><label>صورة بطاقة القسم</label><input class="input" id="catImage" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></div><div class="field"><label>أيقونة القسم</label><input class="input" id="catIcon" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></div><div class="field"><label>بانر القسم</label><input class="input" id="catBanner" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></div></div><label class="check"><input id="catHidden" type="checkbox" ${c?.is_hidden?'checked':''}>إخفاء القسم من المتجر</label><div class="actions" style="margin-top:16px"><button class="primary" id="saveCategory">${id?'حفظ القسم':'إنشاء القسم'}</button>${id&&c?.is_virtual?`<button class="danger" id="deleteCategory">حذف القسم</button>`:''}</div>${id?'<div class="category-delete-note">لا يمكن حذف قسم مرتبط بالمزوّد أو قسم يحتوي منتجات أو أقسامًا داخلية. يمكنك نقله أو إخفاؤه بدلًا من ذلك.</div>':''}`);$('#saveCategory').onclick=()=>saveCategory(id);if($('#deleteCategory'))$('#deleteCategory').onclick=()=>deleteCategory(id)}
  function editCategory(id){const c=categoryById(id);if(c)categoryEditor(c)}
  async function saveCategory(id=0){const b=$('#saveCategory');b.disabled=true;try{const [image,icon,banner]=await Promise.all([fileData($('#catImage').files[0]),fileData($('#catIcon').files[0]),fileData($('#catBanner').files[0])]);const payload={display_name:$('#catName').value.trim(),description:$('#catDescription').value.trim(),parent_id:Number($('#catParent').value||0),sort_order:Number($('#catSort').value||0),badge:$('#catBadge').value.trim(),is_hidden:$('#catHidden').checked,accent:$('#catAccent').value,image,icon,banner};await api(id?`/v1/storefront/admin/category-tree/${id}`:'/v1/storefront/admin/category-tree',{method:id?'PUT':'POST',body:JSON.stringify(payload)});closeModal();toast(id?'تم حفظ القسم':'تم إنشاء القسم');loadCategories()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
  async function deleteCategory(id){if(!confirm('حذف هذا القسم نهائيًا؟'))return;try{await api(`/v1/storefront/admin/category-tree/${id}`,{method:'DELETE'});closeModal();toast('تم حذف القسم');loadCategories()}catch(e){toast(e.message,true)}}
'''


def patch_admin_html(document: str) -> str:
    if "flatCategoryTree" in document:
        return document
    if OLD_SECTION not in document:
        raise RuntimeError("Admin category section marker was not found")
    if OLD_FUNCTIONS not in document:
        raise RuntimeError("Admin category functions marker was not found")
    document = document.replace(OLD_SECTION, NEW_SECTION, 1)
    document = document.replace("  </style>", CATEGORY_ADMIN_CSS + "\n  </style>", 1)
    document = document.replace(OLD_FUNCTIONS, NEW_FUNCTIONS, 1)
    document = document.replace("$('#addBanner').onclick=()=>editBanner();", "$('#addBanner').onclick=()=>editBanner();$('#addCategory').onclick=()=>categoryEditor();", 1)
    return document


__all__ = ["patch_admin_html"]
