# /etc/nginx/conf.d/uchiha-radius-limits.conf
# UCHIHA RADIUS-A v99 / Backend v37
# Load in nginx http{} context.

limit_conn_zone $binary_remote_addr zone=uchiha_radius_conn:10m;
limit_req_zone  $binary_remote_addr zone=uchiha_radius_req:10m rate=100r/s;
