from pathlib import Path
import sys,re
root=Path(sys.argv[1])
js=root/'app/src/main/assets/app-v121.js'
s=js.read_text()
s=s.replace("/* UCHIHA Debt Store v1.2.1 — exact multi-currency balances */","/* UCHIHA Debt Store v1.2.2 — USD/TRY balances + PDF TRY divisor */")
s=s.replace("const V121='1.2.1';","const V121='1.2.2';")
s=s.replace("const CURS=['USD','TRY','SYP'];","const CURS=['USD','TRY'];")
s=s.replace("function blankCur(){return {USD:0,TRY:0,SYP:0};}","function blankCur(){return {USD:0,TRY:0};}")
s=s.replace("const cur=CURS.includes(e.originalCurrency)?e.originalCurrency:'USD';\n    const a=num(e.originalAmount);","if(!CURS.includes(e.originalCurrency))continue;\n    const cur=e.originalCurrency,a=num(e.originalAmount);")
s=s.replace("const cur=CURS.includes(e.originalCurrency)?e.originalCurrency:'USD';out[cur]+=num(e.originalAmount);","if(!CURS.includes(e.originalCurrency))continue;const cur=e.originalCurrency;out[cur]+=num(e.originalAmount);")
s=s.replace("function moneyV121(cur,v){v=num(v);if(cur==='USD')return '$'+fmtFlex(v);if(cur==='TRY')return '₺'+fmtFlex(v);return fmtFlex(v)+' ل.س';}","function moneyV121(cur,v){v=num(v);return cur==='USD'?'$'+fmtFlex(v):'₺'+fmtFlex(v);}")
s=s.replace("<div><span>🇺🇸 USD</span><strong>${moneyV121('USD',b.USD)}</strong></div><div><span>🇹🇷 TRY</span><strong>${moneyV121('TRY',b.TRY)}</strong></div><div><span>🇸🇾 SYP</span><strong>${moneyV121('SYP',b.SYP)}</strong></div>","<div><span>🇺🇸 USD</span><strong>${moneyV121('USD',b.USD)}</strong></div><div><span>🇹🇷 TRY</span><strong>${moneyV121('TRY',b.TRY)}</strong></div>")
s=s.replace("function curInlineV121(b){return `<span class=\"cur-chip-v121 usd\">${moneyV121('USD',b.USD)}</span><span class=\"cur-chip-v121 try\">${moneyV121('TRY',b.TRY)}</span><span class=\"cur-chip-v121 syp\">${moneyV121('SYP',b.SYP)}</span>`;}","function curInlineV121(b){return `<span class=\"cur-chip-v121 usd\">${moneyV121('USD',b.USD)}</span><span class=\"cur-chip-v121 try\">${moneyV121('TRY',b.TRY)}</span>`;}")
s=s.replace("return ledgerRows(clientId).map(e=>{\n    const pay=e.type==='payment',buy=['purchase','opening'].includes(e.type),cur=CURS.includes(e.originalCurrency)?e.originalCurrency:'USD';","return ledgerRows(clientId).filter(e=>CURS.includes(e.originalCurrency)).map(e=>{\n    const pay=e.type==='payment',buy=['purchase','opening'].includes(e.type),cur=e.originalCurrency;")
s=s.replace("${moneyV121('USD',b.USD)} · ${moneyV121('TRY',b.TRY)} · ${moneyV121('SYP',b.SYP)}","${moneyV121('USD',b.USD)} · ${moneyV121('TRY',b.TRY)}")
s=s.replace("let html=oldRenderPurchaseV121();","if(purchaseDraft.currency==='SYP')purchaseDraft.currency='TRY';let html=oldRenderPurchaseV121();html=html.replace(/<option value=\"SYP\"[^>]*>[^<]*<\\/option>/g,'');")
s=s.replace("let html=oldRenderPaymentV121();","if(paymentDraft.currency==='SYP')paymentDraft.currency='TRY';let html=oldRenderPaymentV121();html=html.replace(/<option value=\"SYP\"[^>]*>[^<]*<\\/option>/g,'');")
start=s.index('window.exportClient=function(id,type){')
end=s.index('\n};\n\n})();',start)+3
export_block=r'''window.openPdfExportV122=function(id){
  const c=state.clients.find(x=>x.id===id);if(!c)return;const b=clientCurrencyDebtV121(id),suggested=num(state.rates?.usdTry)>0?fmtFlex(state.rates.usdTry):'';
  openModal(`<h3>تصدير كشف PDF</h3><div class="pdf-convert-v122"><div><span>الدولار</span><b>${moneyV121('USD',b.USD)}</b></div><div><span>التركي</span><b>${moneyV121('TRY',b.TRY)}</b></div></div><div class="form-group"><label class="label">قسمة إجمالي التركي على</label><input id="pdfTryDivisor" class="input amount-input" inputmode="decimal" value="${esc(suggested)}" placeholder="مثال: 40"><div class="small muted" style="margin-top:6px">مثال: ₺4000 ÷ 40 = $100. يظهر التحويل بخانة مستقلة ولا يُضاف للدولار.</div></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">إلغاء</button><button class="btn primary" onclick="confirmPdfExportV122('${id}')">تصدير PDF</button></div>`);
};
window.confirmPdfExportV122=function(id){
  const d=num($('pdfTryDivisor')?.value);if(d<=0){toast('اكتب رقم القسمة');return;}const c=state.clients.find(x=>x.id===id);if(!c)return;const views=ledgerViewRowsV121(id),b=clientCurrencyDebtV121(id),rows=views.map(v=>({date:dateFmt(v.e.date||v.e.createdAt),type:v.pay?'payment':'purchase',typeLabel:v.pay?'دفعة':'شراء',amount:v.amount,currency:v.e.originalCurrency,balance:v.balance,description:entryDescription(v.e),by:v.e.createdBy})),safeName=c.name.replace(/[\\/:*?"<>|]/g,'-'),payload={shop:state.shop,client:c,summary:{usdTryOnly:true,balanceUsd:fmtFlex(b.USD),balanceTry:fmtFlex(b.TRY),tryDivisor:fmtFlex(d),tryConvertedUsd:fmtFlex(b.TRY/d),operations:rows.length},rows};
  closeModal();try{if(window.Android?.exportPdf)Android.exportPdf(JSON.stringify(payload),`كشف-${safeName}-${today()}.pdf`);else toast('PDF متاح داخل APK');}catch(e){toast('تعذر إنشاء PDF');}
};
window.exportClient=function(id,type){
  const c=state.clients.find(x=>x.id===id);if(!c)return;if(type==='pdf'){openPdfExportV122(id);return;}const views=ledgerViewRowsV121(id),rows=views.map(v=>({date:dateFmt(v.e.date||v.e.createdAt),typeLabel:v.pay?'دفعة':'شراء',amount:v.amount,currency:v.e.originalCurrency,balance:v.balance,description:entryDescription(v.e),by:v.e.createdBy})),safeName=c.name.replace(/[\\/:*?"<>|]/g,'-'),headers=['التاريخ','نوع العملية','مبلغ العملية','العملة','الرصيد بعد العملية','البيان','المسجل'],csv=[headers,...rows.map(r=>[r.date,r.typeLabel,r.amount,r.currency,r.balance,r.description,r.by])].map(row=>row.map(csvCell).join(',')).join('\\n');try{if(window.Android?.exportCsv)Android.exportCsv(csv,`كشف-${safeName}-${today()}.csv`);else downloadText('\\ufeff'+csv,`كشف-${safeName}.csv`,'text/csv');}catch(e){toast('تعذر تصدير CSV');}
};'''
s=s[:start]+export_block+s[end:]
inject=r'''
window.renderRates=function(){const r=state.rates;return shell('سعر الصرف',`<div class="card"><div class="client-item"><div class="grow"><b>🇺🇸 USD / 🇹🇷 TRY</b><div class="small muted">للمراجعة والتحويل عند الطلب فقط؛ لا يغير رصيد الدين.</div></div><strong>${r.usdTry?fmt(r.usdTry,3):'—'}</strong></div></div>${isOwner()?`<div class="section-title">تعديل يدوي</div><div class="card"><div class="form-group"><label class="label">1 USD = كم TRY</label><input id="manualTry" class="input" inputmode="decimal" value="${r.usdTry||''}"></div><button class="btn primary full" onclick="saveManualRates()">حفظ السعر اليدوي</button></div>`:''}`);};
window.saveManualRates=function(){const ut=num($('manualTry').value);if(ut<=0){toast('اكتب سعرًا صحيحًا');return;}state.rates.usdTry=ut;state.rates.updatedAt=nowIso();state.rates.source='إدخال يدوي';state.rates.manual=true;saveState();audit('تعديل سعر الصرف','USD/TRY يدوي');render();toast('تم حفظ السعر');};
window.rateText=function(){const r=state.rates;return `💱 سعر الصرف — ${state.shop.name}\n🇺🇸 1 USD = ${r.usdTry?fmt(r.usdTry,3):'—'} TRY\n🕐 آخر تحديث: ${r.updatedAt?dateTimeFmt(r.updatedAt):'غير محدث'}`;};
const oldSettingsV122=window.renderSettings;window.renderSettings=function(){let h=oldSettingsV122();h=h.replace(/\{SHOP\} \{USD_TRY\} \{USD_SYP\} \{TRY_SYP\} \{TIME\}/g,'{SHOP} {USD_TRY} {TIME}');return h;};
window.openEditPurchase=function(id){const e=state.entries.find(x=>x.id===id);if(!e||!['purchase','opening'].includes(e.type))return;if(!can('editPurchase')){toast('لا توجد صلاحية تعديل الشراء');return;}if(e.originalCurrency==='SYP'){toast('العملية القديمة محفوظة في الأرشيف ولا تُعدل من هذه النسخة');return;}openModal(`<h3>تعديل تسجيل الشراء</h3><div class="small muted">الدولار والتركي فقط.</div><div class="amount-row"><div class="form-group"><label class="label">المبلغ</label><input id="editPurAmount" class="input amount-input" inputmode="decimal" value="${esc(e.originalAmount)}"></div><div class="form-group"><label class="label">العملة</label><select id="editPurCurrency" class="select"><option value="USD" ${e.originalCurrency==='USD'?'selected':''}>USD</option><option value="TRY" ${e.originalCurrency==='TRY'?'selected':''}>TRY</option></select></div></div><div class="form-group"><label class="label">البيان</label><input id="editPurDesc" class="input" value="${esc(e.description||'')}"></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">إلغاء</button><button class="btn primary" onclick="savePurchaseEdit('${e.id}')">حفظ التعديل</button></div>`);};
'''
s=s.replace('\n})();',inject+'\n})();')
js.write_text(s)
css=root/'app/src/main/assets/app-v110.css'
c=css.read_text()+"\n.currency-balance-grid-v121{grid-template-columns:repeat(2,1fr)!important}.pdf-convert-v122{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0 14px}.pdf-convert-v122>div{background:#0f161f;border:1px solid #26313f;border-radius:12px;padding:10px;text-align:center}.pdf-convert-v122 span{display:block;font-size:10px;color:#90a1b7;margin-bottom:4px}.pdf-convert-v122 b{font-size:18px;direction:ltr;display:block}\n"
css.write_text(c)
bg=root/'app/build.gradle'; b=bg.read_text().replace('versionCode 9','versionCode 10').replace("versionName '1.2.1'","versionName '1.2.2'");bg.write_text(b)
java=root/'app/src/main/java/com/uchiha/debtstore/MainActivity.java'; j=java.read_text()
needle='''                    if(pageNo==1){\n                        float gap=4f,cardW=(pageW-2f*margin-2f*gap)/3f;\n                        boolean multiCurrency=summary!=null && summary.optBoolean("multiCurrency",false);'''
replacement='''                    boolean usdTryOnly=summary!=null && summary.optBoolean("usdTryOnly",false);\n                    if(pageNo==1){\n                        float gap=4f,cardW=(pageW-2f*margin-2f*gap)/3f;\n                        if(usdTryOnly){\n                            String[] labs={"الرصيد بالدولار","الرصيد بالتركي","عدد العمليات"};\n                            String[] vals={"$"+summary.optString("balanceUsd","0"),"₺"+summary.optString("balanceTry","0"),String.valueOf(summary.optInt("operations",rows.length()))};\n                            for(int i=0;i<3;i++){float left=pageW-margin-(i+1)*cardW-i*gap;p.setStyle(Paint.Style.FILL);p.setColor(panel);c.drawRoundRect(left,cardTop,left+cardW,cardTop+cardH,7,7,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1f);p.setColor(border);c.drawRoundRect(left,cardTop,left+cardW,cardTop+cardH,7,7,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));p.setTextSize(9.2f);p.setColor(muted);c.drawText(labs[i],left+cardW/2f,cardTop+17,p);p.setColor(i==1?green:text);p.setTextSize(16.5f);c.drawText(trim(vals[i],18),left+cardW/2f,cardTop+43,p);}\n                            float ct=cardTop+cardH+6;p.setStyle(Paint.Style.FILL);p.setColor(panel);c.drawRoundRect(margin,ct,pageW-margin,ct+38,7,7,p);p.setStyle(Paint.Style.STROKE);p.setColor(border);c.drawRoundRect(margin,ct,pageW-margin,ct+38,7,7,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.RIGHT);p.setColor(muted);p.setTextSize(9f);c.drawText("تحويل التركي بالدولار: ₺"+summary.optString("balanceTry","0")+" ÷ "+summary.optString("tryDivisor","0"),pageW-margin-8,ct+15,p);p.setColor(blue);p.setTextSize(16f);c.drawText("$"+summary.optString("tryConvertedUsd","0"),pageW-margin-8,ct+32,p);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(7.5f);p.setColor(muted);c.drawText("خانة مستقلة — غير مضافة للدولار",margin+8,ct+25,p);p.setTextAlign(Paint.Align.RIGHT);\n                        }else{\n                        boolean multiCurrency=summary!=null && summary.optBoolean("multiCurrency",false);'''
if needle not in j: raise SystemExit('PDF needle missing')
j=j.replace(needle,replacement,1)
marker='''                        p.setTextAlign(Paint.Align.RIGHT);\n                    }\n                    float yTop=pageNo==1?tableTop:58;'''
if marker not in j: raise SystemExit('PDF close marker missing')
j=j.replace(marker,'''                        p.setTextAlign(Paint.Align.RIGHT);\n                        }\n                    }\n                    float yTop=pageNo==1?(usdTryOnly?cardTop+cardH+50:tableTop):58;''',1)
j=j.replace('''                                String sy=(sums==null?"0":sums.optString("SYP","0"))+" ل.س";\n                                p.setTextSize(8.6f);c.drawText(trim(usd,16),left+cardW/2f,cardTop+30,p);\n                                c.drawText(trim(tr,16),left+cardW/2f,cardTop+42,p);\n                                c.drawText(trim(sy,16),left+cardW/2f,cardTop+54,p);''','''                                p.setTextSize(9.2f);c.drawText(trim(usd,16),left+cardW/2f,cardTop+33,p);\n                                c.drawText(trim(tr,16),left+cardW/2f,cardTop+49,p);''')
java.write_text(j)
print('PATCH_V122_OK')
