-- UCHIHA Builder migration 032: a Telegram bot identity can belong to only one
-- purchased AI-bot instance. Token strings can be regenerated by BotFather, so
-- token fingerprint uniqueness alone is not sufficient.

CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_bot_instances_telegram_bot_id_unique
  ON ai_bot_instances (telegram_bot_id)
  WHERE telegram_bot_id IS NOT NULL;
