const { spawnSync } = require("child_process");
const path = require("path");

const root = path.join(__dirname,"..");
const commands = [
  ["node",["--test",...require("fs").readdirSync(require("path").join(root,"tests")).filter(x=>x.endsWith(".test.js")).map(x=>"tests/"+x)]],
  ["node",["scripts/smoke.js"]],
  ["node",["scripts/route-audit.js"]],
  ["node",["scripts/frontend-security-audit.js"]],
  ["node",["scripts/release-metadata-audit.js"]],
  ["node",["scripts/secret-scan.js"]],
  ["node",["scripts/deploy-security-audit.js"]],
  ["node",["--check","server.js"]],
  ["node",["--check","store.js"]],
  ["node",["--check","providers/http.js"]],
  ["node",["--check","providers/index.js"]],
  ["node",["--check","lib/publicViews.js"]],
  ["node",["--check","lib/backupFormat.js"]],
  ["node",["--check","lib/backupStatus.js"]],
  ["node",["--check","lib/backupCrypto.js"]],
  ["node",["--check","lib/stateSnapshot.js"]],
  ["node",["--check","lib/financialMirror.js"]],
  ["node",["--check","lib/financialJournal.js"]],
  ["node",["--check","lib/walletAuthority.js"]],
  ["node",["--check","lib/businessAuthority.js"]],
  ["node",["--check","lib/postgresRecovery.js"]],
  ["node",["--check","lib/auditChain.js"]],
  ["node",["--check","lib/checkoutPolicy.js"]],
  ["node",["--check","lib/csv.js"]],
  ["node",["--check","lib/integrity.js"]],
  ["node",["--check","lib/keyedLock.js"]],
  ["node",["--check","lib/migrations.js"]],
  ["node",["--check","lib/outboundPolicy.js"]],
  ["node",["--check","lib/topupPolicy.js"]],
  ["node",["--check","lib/orderPolicy.js"]],
  ["node",["--check","lib/productInput.js"]],
  ["node",["--check","lib/adminFinancialPolicy.js"]],
  ["node",["--check","lib/adminOrderPolicy.js"]],
  ["node",["--check","lib/adminTopupPolicy.js"]],
  ["node",["--check","lib/adminBroadcastPolicy.js"]],
  ["node",["--check","lib/adminAutomationPolicy.js"]],
  ["node",["--check","lib/botUserPolicy.js"]],
  ["node",["--check","lib/providerOutcomePolicy.js"]],
  ["node",["--check","scripts/release-metadata-audit.js"]],
  ["node",["--check","scripts/secret-scan.js"]],
  ["node",["--check","scripts/deploy-security-audit.js"]],
  ["node",["--check","../deploy/generate-secrets.js"]],
  ["node",["--check","scripts/provider-simulator.js"]],
  ["node",["--check","scripts/validate-backup.js"]],
  ["node",["--check","scripts/send-payment-webhook.js"]],
  ["node",["--check","scripts/http-e2e.js"]],
  ["node",["--check","scripts/postgres-e2e.js"]],
  ["node",["--check","scripts/postgres-lock-probe.js"]],
  ["node",["--check","scripts/state-verify.js"]],
  ["node",["--check","scripts/state-history.js"]],
  ["node",["--check","scripts/state-rollback.js"]],
  ["node",["--check","scripts/financial-mirror-verify.js"]],
  ["node",["--check","scripts/financial-mirror-rebuild.js"]],
  ["node",["--check","scripts/financial-journal-verify.js"]],
  ["node",["--check","scripts/wallet-authority-verify.js"]],
  ["node",["--check","scripts/business-authority-verify.js"]],
  ["node",["--check","scripts/backup.js"]],
  ["node",["--check","scripts/backup-worker.js"]],
  ["node",["--check","scripts/check-backup-health.js"]],
  ["node",["--check","scripts/restore.js"]],
  ["node",["--check","../bot/bot.js"]],
  ["node",["--check","../miniapp/app.js"]],
  ["node",["--check","../miniapp/sw.js"]],
  ["node",["--check","../admin/admin.js"]]
];
for(const [cmd,args] of commands){
  const r=spawnSync(cmd,args,{cwd:root,stdio:"inherit"});
  if(r.status!==0)process.exit(r.status||1);
}
console.log("Game Zone release check: OK");
